# Generated by Django 5.0.1 on 2026-08-25 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='Award', max_length=64)),
                ('category', models.CharField(choices=[('STREAK', 'Streak & Consistency'), ('MASTERY', 'Subject Mastery'), ('SPEED', 'Speed & Precision'), ('COMMUNITY', 'Community Contributor')], default='MASTERY', max_length=32)),
                ('xp_bonus', models.IntegerField(default=100)),
                ('requirement', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'lh_badges',
            },
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('target_xp', models.IntegerField(default=100)),
                ('earned_xp', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'lh_daily_goals',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('current_progress', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'lh_user_badges',
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('source', models.CharField(default='TEST_PASS', max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lh_xp_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
