// Mocks generated by Mockito 5.4.6 from annotations
// in learning_hub/test/features/gamification/gamification_logic_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:learning_hub/core/network/network_info.dart' as _i3;
import 'package:learning_hub/core/services/sync_service.dart' as _i2;
import 'package:learning_hub/features/gamification/data/datasources/gamification_data_sources.dart'
    as _i5;
import 'package:learning_hub/features/gamification/data/models/gamification_models.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i3.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [GamificationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamificationRemoteDataSource extends _i1.Mock
    implements _i5.GamificationRemoteDataSource {
  MockGamificationRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int> getUserXP() => (super.noSuchMethod(
        Invocation.method(
          #getUserXP,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i6.AchievementModel>> getAchievements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAchievements,
          [],
        ),
        returnValue: _i4.Future<List<_i6.AchievementModel>>.value(
            <_i6.AchievementModel>[]),
      ) as _i4.Future<List<_i6.AchievementModel>>);

  @override
  _i4.Future<List<_i6.LeaderboardEntryModel>> getLeaderboard(String? period) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLeaderboard,
          [period],
        ),
        returnValue: _i4.Future<List<_i6.LeaderboardEntryModel>>.value(
            <_i6.LeaderboardEntryModel>[]),
      ) as _i4.Future<List<_i6.LeaderboardEntryModel>>);

  @override
  _i4.Future<void> unlockAchievement(String? achievementId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlockAchievement,
          [achievementId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addXP(int? amount) => (super.noSuchMethod(
        Invocation.method(
          #addXP,
          [amount],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [GamificationLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamificationLocalDataSource extends _i1.Mock
    implements _i5.GamificationLocalDataSource {
  MockGamificationLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int> getLastKnownXP() => (super.noSuchMethod(
        Invocation.method(
          #getLastKnownXP,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> cacheXP(int? xp) => (super.noSuchMethod(
        Invocation.method(
          #cacheXP,
          [xp],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.AchievementModel>> getCachedAchievements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedAchievements,
          [],
        ),
        returnValue: _i4.Future<List<_i6.AchievementModel>>.value(
            <_i6.AchievementModel>[]),
      ) as _i4.Future<List<_i6.AchievementModel>>);

  @override
  _i4.Future<void> cacheAchievements(
          List<_i6.AchievementModel>? achievements) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheAchievements,
          [achievements],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cacheLeaderboard(
    List<_i6.LeaderboardEntryModel>? leaderboard, {
    String? period = 'all_time',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheLeaderboard,
          [leaderboard],
          {#period: period},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.LeaderboardEntryModel>> getCachedLeaderboard(
          {String? period = 'all_time'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedLeaderboard,
          [],
          {#period: period},
        ),
        returnValue: _i4.Future<List<_i6.LeaderboardEntryModel>>.value(
            <_i6.LeaderboardEntryModel>[]),
      ) as _i4.Future<List<_i6.LeaderboardEntryModel>>);

  @override
  _i4.Future<int> getStreak() => (super.noSuchMethod(
        Invocation.method(
          #getStreak,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> cacheStreak(int? streak) => (super.noSuchMethod(
        Invocation.method(
          #cacheStreak,
          [streak],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<int> watchXP() => (super.noSuchMethod(
        Invocation.method(
          #watchXP,
          [],
        ),
        returnValue: _i4.Stream<int>.empty(),
      ) as _i4.Stream<int>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i2.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<DateTime?> get lastSyncTime => (super.noSuchMethod(
        Invocation.getter(#lastSyncTime),
        returnValue: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);

  @override
  int get pendingCount => (super.noSuchMethod(
        Invocation.getter(#pendingCount),
        returnValue: 0,
      ) as int);

  @override
  int get failedCount => (super.noSuchMethod(
        Invocation.getter(#failedCount),
        returnValue: 0,
      ) as int);

  @override
  List<_i2.SyncItem> get pendingItems => (super.noSuchMethod(
        Invocation.getter(#pendingItems),
        returnValue: <_i2.SyncItem>[],
      ) as List<_i2.SyncItem>);

  @override
  List<_i2.SyncItem> get failedItems => (super.noSuchMethod(
        Invocation.getter(#failedItems),
        returnValue: <_i2.SyncItem>[],
      ) as List<_i2.SyncItem>);

  @override
  _i4.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void registerHandler(
    String? type,
    _i4.Future<bool> Function(_i2.SyncItem)? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #registerHandler,
          [
            type,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> queue({
    required String? type,
    required String? action,
    required Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queue,
          [],
          {
            #type: type,
            #action: action,
            #data: data,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.SyncResult> syncNow() => (super.noSuchMethod(
        Invocation.method(
          #syncNow,
          [],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncNow,
            [],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<void> retryFailed() => (super.noSuchMethod(
        Invocation.method(
          #retryFailed,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> remove(String? id) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
