# Generated by Django 5.0.1 on 2026-01-05 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(max_length=50)),
                ("criteria_type", models.CharField(max_length=50)),
                ("criteria_value", models.PositiveIntegerField()),
                ("xp_reward", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "badges",
            },
        ),
        migrations.CreateModel(
            name="Streak",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("last_activity_date", models.DateField(null=True)),
            ],
            options={
                "db_table": "streaks",
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_badges",
            },
        ),
        migrations.CreateModel(
            name="UserXP",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_xp", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveIntegerField(default=1)),
                ("weekly_xp", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "user_xp",
            },
        ),
    ]
