# Generated by Django 5.0.1 on 2026-07-04 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['criteria_type'], name='idx_badge_criteria'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['-xp_reward'], name='idx_badge_xp'),
        ),
        migrations.AddIndex(
            model_name='guild',
            index=models.Index(fields=['-total_xp'], name='idx_guild_xp'),
        ),
        migrations.AddIndex(
            model_name='guild',
            index=models.Index(fields=['-level', '-total_xp'], name='idx_guild_level'),
        ),
        migrations.AddIndex(
            model_name='guild',
            index=models.Index(fields=['leader'], name='idx_guild_leader'),
        ),
        migrations.AddIndex(
            model_name='guildmembership',
            index=models.Index(fields=['guild', '-contribution_xp'], name='idx_guildmember_contrib'),
        ),
        migrations.AddIndex(
            model_name='guildmembership',
            index=models.Index(fields=['user', '-created_at'], name='idx_guildmember_user'),
        ),
        migrations.AddIndex(
            model_name='guildmembership',
            index=models.Index(fields=['role'], name='idx_guildmember_role'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['-current_streak'], name='idx_streak_current'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['-longest_streak'], name='idx_streak_longest'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['last_activity_date'], name='idx_streak_activity'),
        ),
        migrations.AddIndex(
            model_name='userxp',
            index=models.Index(fields=['-total_xp', 'user'], name='idx_userxp_leaderboard'),
        ),
        migrations.AddIndex(
            model_name='userxp',
            index=models.Index(fields=['-weekly_xp'], name='idx_userxp_weekly'),
        ),
        migrations.AddIndex(
            model_name='userxp',
            index=models.Index(fields=['level', '-total_xp'], name='idx_userxp_level_xp'),
        ),
        migrations.AddIndex(
            model_name='userxp',
            index=models.Index(fields=['last_activity_date'], name='idx_userxp_activity'),
        ),
    ]
