# Generated by Django 5.2.10 on 2026-02-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_phase6_analytics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streak',
            old_name='max_streak',
            new_name='longest_streak',
        ),
    ]
