# Generated by Django 5.2.10 on 2026-01-25 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models

try:
    import pgvector.django.vector
    VectorField = pgvector.django.vector.VectorField
except ImportError:
    # Fallback for SQLite dev/test: use TextField as a stand-in
    VectorField = lambda **kwargs: models.TextField(default="", blank=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEmbedding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('chunk_text', models.TextField(help_text='Text segment used for embedding')),
                ('embedding', VectorField(dimensions=384, help_text='Semantic Vector')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'course_embeddings',
            },
        ),
    ]
