# Generated by Django 5.2.10 on 2026-01-25 17:01

from django.db import migrations, models

try:
    import pgvector.django.vector
    VectorField = pgvector.django.vector.VectorField
except ImportError:
    VectorField = lambda **kwargs: models.TextField(default="", blank=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_courseembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseembedding',
            name='embedding',
            field=VectorField(dimensions=768, help_text='Semantic Vector'),
        ),
    ]
