# Generated by Django 5.2.10 on 2026-02-01 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_alter_courseembedding_embedding'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('gamification', '0002_phase6_analytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('weekly', 'Weekly Challenge'), ('monthly', 'Monthly Challenge'), ('event', 'Special Event'), ('learning', 'Learning Sprint')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('legendary', 'Legendary')], default='medium', max_length=20)),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('requirements', models.JSONField(default=dict, help_text='\n        Example: {"action": "lesson_complete", "count": 5, "course_id": null}\n    ')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('completion_count', models.PositiveIntegerField(default=0)),
                ('badge_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='gamification.badge')),
            ],
            options={
                'db_table': 'challenges',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningInsight',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engagement_score', models.FloatField(default=0.0, help_text='Overall engagement level')),
                ('consistency_score', models.FloatField(default=0.0, help_text='How regularly user studies')),
                ('completion_rate', models.FloatField(default=0.0, help_text='Lessons completed vs started')),
                ('preferred_time', models.CharField(blank=True, help_text='morning/afternoon/evening/night', max_length=20)),
                ('preferred_duration', models.PositiveIntegerField(default=30, help_text='Avg session length in minutes')),
                ('learning_velocity', models.FloatField(default=1.0, help_text='Speed relative to average')),
                ('predicted_topics', models.JSONField(default=list, help_text='Topics user might enjoy')),
                ('strength_areas', models.JSONField(default=list, help_text="User's strong subjects")),
                ('improvement_areas', models.JSONField(default=list, help_text='Areas needing work')),
                ('burnout_risk', models.FloatField(default=0.0, help_text='Risk of user disengaging')),
                ('total_learning_hours', models.FloatField(default=0.0)),
                ('weekly_average_hours', models.FloatField(default=0.0)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_insight', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_insights',
            },
        ),
        migrations.CreateModel(
            name='RemedialPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_slug', models.CharField(max_length=100)),
                ('root_cause_analysis', models.TextField(help_text='AI Analysis of weak areas')),
                ('suggested_actions', models.JSONField(default=list)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'remedial_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('lesson_view', 'Lesson Viewed'), ('lesson_complete', 'Lesson Completed'), ('quiz_start', 'Quiz Started'), ('quiz_complete', 'Quiz Completed'), ('code_submit', 'Code Submitted'), ('code_run', 'Code Run'), ('ai_question', 'AI Question Asked'), ('search', 'Search Performed'), ('note_create', 'Note Created'), ('bookmark', 'Bookmark Added'), ('session_start', 'Session Started'), ('session_end', 'Session Ended')], max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, help_text='Browser/App session ID', max_length=64)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Time spent on activity')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context')),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action', 'created_at'], name='activity_lo_user_id_9a0a50_idx'), models.Index(fields=['session_id'], name='activity_lo_session_45d5f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Current progress count')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ai_engine.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_participants',
                'unique_together': {('challenge', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LearningSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('days_json', models.JSONField(default=dict)),
                ('goal', models.CharField(help_text='Goal for this week', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_schedules',
                'ordering': ['-week_start_date'],
                'unique_together': {('user', 'week_start_date')},
            },
        ),
    ]
