# Generated by Django 5.2.10 on 2026-02-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_phase6_analytics'),
    ]

    operations = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Only enable pgvector extension when running on PostgreSQL
        try:
            from pgvector.django import VectorExtension
            self.operations = [VectorExtension()]
        except ImportError:
            # SQLite/other backends: skip the pgvector extension
            self.operations = []
