# Generated by Django 5.2.10 on 2026-02-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0006_alter_courseembedding_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninginsight',
            name='ai_narrative',
            field=models.TextField(blank=True, default='', help_text='AI-generated summary of learning patterns'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(choices=[('daily', 'Daily Quest'), ('weekly', 'Weekly Challenge'), ('monthly', 'Monthly Challenge'), ('event', 'Special Event'), ('learning', 'Learning Sprint')], max_length=20),
        ),
    ]
