# Generated by Django 5.0.1 on 2026-03-18 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

try:
    import pgvector.django.vector
    VectorField = pgvector.django.vector.VectorField
except ImportError:
    VectorField = lambda **kwargs: models.TextField(default="", blank=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0007_learninginsight_ai_narrative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticCache',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField(help_text='The exact prompt or query asked by the user')),
                ('response_payload', models.JSONField(help_text='The structured JSON or text response from the LLM')),
                ('query_embedding', VectorField(dimensions=384, help_text='Semantic Vector of the query')),
            ],
            options={
                'db_table': 'semantic_cache',
            },
        ),
        migrations.CreateModel(
            name='HumanPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(help_text='The context or question posed to the AI')),
                ('chosen', models.TextField(help_text='The AI generation that the user preferred (Thumbs Up)')),
                ('rejected', models.TextField(help_text='The AI generation that the user rejected (Thumbs Down)')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('applied_to_dpo', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_human_preferences',
                'ordering': ['-created_at'],
            },
        ),
    ]
