# Generated by Django 5.0.1 on 2026-04-17 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0009_activitylog_is_active_challengeparticipant_is_active_and_more'),
        ('courses', '0011_certificate_is_active_course_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('behavior_type', models.CharField(choices=[('course_view', 'Course Viewed'), ('course_click', 'Course Clicked'), ('search', 'Search Performed'), ('category_filter', 'Category Filtered'), ('difficulty_filter', 'Difficulty Filtered'), ('price_filter', 'Price Filtered'), ('enroll', 'Course Enrolled'), ('wishlist', 'Added to Wishlist'), ('review_view', 'Reviews Viewed'), ('instructor_view', 'Instructor Profile Viewed'), ('time_spent', 'Time Spent on Page')], max_length=50)),
                ('value', models.CharField(blank=True, help_text='Search query or filter value', max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Time spent on action')),
                ('source_page', models.CharField(blank=True, help_text='Page where action originated', max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_behaviors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'behavior_type', 'created_at'], name='user_behavi_user_id_80cffe_idx'), models.Index(fields=['course', 'behavior_type'], name='user_behavi_course__7a7f9d_idx')],
            },
        ),
    ]
