# Generated by Django 5.0.1 on 2026-04-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add database indexes for AI engine query performance optimization.
    """

    dependencies = [
        ('ai_engine', '0010_userbehavior'),
    ]

    operations = [
        # ActivityLog supplementary indexes
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(
                fields=['created_at'],
                name='idx_activitylog_created',
            ),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(
                fields=['user', 'created_at'],
                name='idx_activitylog_user_date',
            ),
        ),
        
        # UserBehavior supplementary indexes
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(
                fields=['created_at'],
                name='idx_behavior_created',
            ),
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(
                fields=['user', 'course'],
                name='idx_behavior_user_course',
            ),
        ),
        
        # Challenge indexes
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(
                fields=['starts_at', 'is_active'],
                name='idx_challenge_starts_active',
            ),
        ),
        
        # ChallengeParticipant indexes
        migrations.AddIndex(
            model_name='challengeparticipant',
            index=models.Index(
                fields=['user', 'is_completed'],
                name='idx_challengepart_user_done',
            ),
        ),
        
        # LearningInsight indexes
        migrations.AddIndex(
            model_name='learninginsight',
            index=models.Index(
                fields=['user'],
                name='idx_insight_user',
            ),
        ),
    ]
