# Generated by Django 5.0.1 on 2026-04-23 17:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0011_add_performance_indexes'),
        ('courses', '0013_remove_category_idx_category_active_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_actions', models.PositiveIntegerField(default=0)),
                ('learning_actions', models.PositiveIntegerField(default=0)),
                ('social_actions', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_user_engagement',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('preferred_difficulty', models.CharField(default='intermediate', max_length=20)),
                ('preferred_format', models.CharField(default='video', max_length=20)),
                ('preferred_duration', models.PositiveIntegerField(default=30)),
                ('adaptation_frequency', models.CharField(default='moderate', max_length=20)),
                ('difficulty_adjustment', models.CharField(default='gradual', max_length=20)),
            ],
            options={
                'db_table': 'ai_user_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('quizzes_passed', models.PositiveIntegerField(default=0)),
                ('courses_enrolled', models.PositiveIntegerField(default=0)),
                ('average_quiz_score', models.FloatField(default=0.0)),
                ('learning_style', models.CharField(default='visual', max_length=20)),
                ('learning_velocity', models.CharField(default='normal', max_length=20)),
                ('engagement_score', models.FloatField(default=0.5)),
            ],
            options={
                'db_table': 'ai_user_profiles',
            },
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='idx_activitylog_created',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='idx_activitylog_user_date',
        ),
        migrations.RemoveIndex(
            model_name='challenge',
            name='idx_challenge_starts_active',
        ),
        migrations.RemoveIndex(
            model_name='challengeparticipant',
            name='idx_challengepart_user_done',
        ),
        migrations.RemoveIndex(
            model_name='learninginsight',
            name='idx_insight_user',
        ),
        migrations.RemoveIndex(
            model_name='userbehavior',
            name='idx_behavior_created',
        ),
        migrations.RemoveIndex(
            model_name='userbehavior',
            name='idx_behavior_user_course',
        ),
        migrations.AddField(
            model_name='userengagement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_engagement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, to='courses.category'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preferences_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='courses_interacted',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='courses.course'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userengagement',
            unique_together={('user', 'date')},
        ),
    ]
