# Generated by Django 5.0.1 on 2026-06-08 06:26

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0012_userengagement_userpreferences_userprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseembedding",
            name="embedding",
            field=pgvector.django.VectorField(
                dimensions=384, help_text="Semantic Vector"
            ),
        ),
        migrations.AlterField(
            model_name="semanticcache",
            name="query_embedding",
            field=pgvector.django.VectorField(
                dimensions=384, help_text="Semantic Vector of the query"
            ),
        ),
    ]
