# Generated by Django 5.0.1 on 2026-05-15 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('language', models.CharField(default='en', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'exam_countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('full_name', models.CharField(blank=True, max_length=300)),
                ('pattern', models.JSONField(default=dict, help_text='Exam pattern: sections, marks, timing')),
                ('difficulty_distribution', models.JSONField(default=dict, help_text='Target difficulty distribution for generated tests')),
                ('official_website', models.URLField(blank=True)),
                ('conducting_body', models.CharField(blank=True, max_length=200)),
                ('frequency', models.CharField(default='annual', max_length=20)),
                ('next_exam_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('popularity_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.country')),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-popularity_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weightage', models.FloatField(default=0, help_text='Percentage weight in exam (0-100)')),
                ('expected_questions', models.IntegerField(default=0, help_text='Expected questions in exam')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='exams.exam')),
            ],
            options={
                'db_table': 'exam_subjects',
                'ordering': ['exam', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty_trend', models.JSONField(blank=True, default=dict)),
                ('question_count', models.IntegerField(default=0)),
                ('avg_difficulty', models.FloatField(default=0.5, help_text='Average difficulty of questions (0-1)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='exams.topic')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='exams.subject')),
            ],
            options={
                'db_table': 'exam_topics',
                'ordering': ['subject', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['country', 'is_active'], name='exams_country_c8285a_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_active', 'is_featured'], name='exams_is_acti_638e91_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['code'], name='exams_code_54eb1a_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['exam', 'is_active'], name='exam_subjec_exam_id_6c2d59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('exam', 'code')},
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['subject', 'is_active'], name='exam_topics_subject_289d95_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['parent'], name='exam_topics_parent__b5143a_idx'),
        ),
    ]
