# Generated by Django 6.0 on 2026-01-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_feedback',
            field=models.JSONField(blank=True, help_text='AI generated code review and hints', null=True),
        ),
    ]
