# Generated by Django 5.2.10 on 2026-01-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0004_alter_problem_options_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
