# Generated by Django 5.2.10 on 2026-01-25 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0005_alter_tag_options_alter_problem_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-submitted_at'], name='dsa_submiss_user_id_ed9615_idx'),
        ),
    ]
