version: "3.8"

services:
  frontend:
    build: ./windows_app
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend
      - daphne
    networks:
      - learning_hub_network

  payment_service:
    build: ./windows_app/backend/payment_service
    ports:
      - "8080:8080"
    networks:
      - learning_hub_network

  backend:
    build: ./conductor
    command: gunicorn config.wsgi:application --config gunicorn_config.py
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    networks:
      - learning_hub_network

  daphne:
    build: ./conductor
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    networks:
      - learning_hub_network

  db:
    image: pgvector/pgvector:pg16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-conductor}
      - POSTGRES_USER=${POSTGRES_USER:-conductor}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set}
    networks:
      - learning_hub_network

  redis:
    image: redis:alpine
    networks:
      - learning_hub_network

  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - "9121:9121"
    command:
      - "--redis.addr=redis:6379"
    depends_on:
      - redis
    networks:
      - learning_hub_network

  celery_worker:
    build: ./conductor
    command: celery -A config worker -l info
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    networks:
      - learning_hub_network

  celery-exporter:
    image: danihodovic/celery-exporter
    command: --broker-url=redis://redis:6379/0
    ports:
      - "9808:9808"
    depends_on:
      - redis
      - celery_worker

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - backend
    networks:
      - learning_hub_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    depends_on:
      - prometheus
    networks:
      - learning_hub_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  learning_hub_network:
    driver: bridge
