[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
norecursedirs = venv .venv .env .git .vs test_logs _test_logs .mypy_cache .pytest_cache build dist
addopts = --ignore-glob=*.txt -p no:schemathesis --ds=config.settings.test
asyncio_mode = auto
pythonpath = .
testpaths = apps tests
django_find_project = false
