[pytest]
DJANGO_SETTINGS_MODULE = config.settings.development
python_files = tests.py test_*.py *_tests.py
norecursedirs = venv .env .git test_logs _test_logs .mypy_cache .pytest_cache
addopts = --reuse-db --nomigrations --cov=. --cov-report=html
passenv =
    DATABASE_URL
    REDIS_URL
