# Generated by Django 5.2.10 on 2026-02-01 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0008_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Client-generated unique ID for the viewing session', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_lesson_activity',
                'indexes': [models.Index(fields=['user', 'lesson'], name='analytics_l_user_id_981bbd_idx'), models.Index(fields=['started_at'], name='analytics_l_started_37308b_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoInteraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('play', 'Play'), ('pause', 'Pause'), ('seek', 'Seek'), ('complete', 'Complete'), ('heartbeat', 'Heartbeat')], max_length=20)),
                ('video_timestamp', models.FloatField(help_text='Position in video (seconds)')),
                ('real_timestamp', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_interactions', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_video_interactions',
                'indexes': [models.Index(fields=['lesson', 'video_timestamp'], name='analytics_v_lesson__35b1df_idx')],
            },
        ),
    ]
