# Generated by Django 5.0.1 on 2026-06-04 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videointeraction',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_interactions', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='videointeraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lessonactivity',
            index=models.Index(fields=['user', 'lesson'], name='analytics_l_user_id_981bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonactivity',
            index=models.Index(fields=['started_at'], name='analytics_l_started_37308b_idx'),
        ),
        migrations.AddIndex(
            model_name='videointeraction',
            index=models.Index(fields=['lesson', 'video_timestamp'], name='analytics_v_lesson__35b1df_idx'),
        ),
    ]
