# Generated by Django 5.0.1 on 2026-08-25 07:14

import apps.ecommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.CharField(default=apps.ecommerce.models.generate_cart_id, max_length=64, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lh_carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.CharField(default=apps.ecommerce.models.generate_item_id, max_length=64, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lh_cart_items',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.CharField(default=apps.ecommerce.models.generate_cert_id, max_length=64, primary_key=True, serialize=False)),
                ('certificate_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=128)),
                ('download_url', models.URLField(max_length=500)),
                ('is_revoked', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lh_certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.CharField(default=apps.ecommerce.models.generate_contest_id, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=120)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('participants', models.IntegerField(default=120)),
                ('problem_count', models.IntegerField(default=4)),
                ('prize', models.CharField(blank=True, default='₹50,000 Prize Pool', max_length=255)),
                ('difficulty', models.CharField(default='medium', max_length=32)),
            ],
            options={
                'db_table': 'lh_contests',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('discount_percent', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lh_coupons',
            },
        ),
        migrations.CreateModel(
            name='Web3Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(blank=True, default='', max_length=128)),
                ('wallet_address', models.CharField(blank=True, default='0x0000000000000000000000000000000000000000', max_length=128)),
                ('network', models.CharField(default='Polygon PoS', max_length=64)),
                ('nft_certificates', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lh_web3_profiles',
            },
        ),
    ]
