# Generated by Django 5.0.1 on 2026-09-07 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_certificate_course_instructor_bio_and_more'),
        ('ecommerce', '0004_order_idempotency_key_order_webhook_received_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course'),
        ),
    ]
