apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "learning-hub.fullname" . }}-backend
  labels:
    {{- include "learning-hub.labels" . | nindent 4 }}
    component: backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "learning-hub.selectorLabels" . | nindent 6 }}
      component: backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "learning-hub.selectorLabels" . | nindent 8 }}
        component: backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "learning-hub.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["gunicorn"]
          args: ["config.wsgi:application", "--bind", "0.0.0.0:8000"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.env.DJANGO_SETTINGS_MODULE }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "learning-hub.fullname" . }}-secrets
                  key: database-url
            - name: REDIS_URL
              value: "redis://{{ .Release.Name }}-redis-master:6379/0"
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "learning-hub.fullname" . }}-secrets
                  key: gemini-api-key
          livenessProbe:
            httpGet:
              path: /health/
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
