# Generated by Django 5.0.1 on 2026-07-04 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='course_text_search_idx',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'order'], name='idx_category_active'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'order'], name='idx_category_parent'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='idx_category_slug'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['content_type'], name='idx_lesson_type'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_preview'], name='idx_lesson_preview'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_pro_only'], name='idx_lesson_pro'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['title'], name='idx_lesson_title'),
        ),
        migrations.AddIndex(
            model_name='lessoncompletion',
            index=models.Index(fields=['user', '-completed_at'], name='idx_lessoncomp_user'),
        ),
        migrations.AddIndex(
            model_name='lessoncompletion',
            index=models.Index(fields=['lesson', '-completed_at'], name='idx_lessoncomp_lesson'),
        ),
        migrations.AddIndex(
            model_name='lessoncompletion',
            index=models.Index(fields=['-completed_at'], name='idx_lessoncomp_recent'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', '-created_at'], name='idx_module_recent'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['title'], name='idx_module_title'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['course', '-created_at'], name='idx_review_course'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='idx_review_user'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['course', '-rating'], name='idx_review_course_rating'),
        ),
    ]
