# Generated by Django 5.2.10 on 2026-01-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Semantic vector embedding (384-dim)', null=True),
        ),
    ]
