# Generated by Django 5.0.1 on 2026-08-23 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNote',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp_seconds', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'course_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Document'), ('code', 'Code Repository / Zip'), ('slides', 'Lecture Slides'), ('link', 'External Reference Link'), ('dataset', 'Dataset File')], default='pdf', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='courses/resources/')),
                ('external_url', models.URLField(blank=True)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'course_resources',
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user', '-issued_at'], name='idx_cert_user'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['course', '-issued_at'], name='idx_cert_course'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_code'], name='idx_cert_code'),
        ),
        migrations.AddField(
            model_name='coursenote',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursenote',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='coursenote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='courses.lesson'),
        ),
        migrations.AddIndex(
            model_name='coursenote',
            index=models.Index(fields=['user', 'course'], name='course_note_user_id_aa186a_idx'),
        ),
        migrations.AddIndex(
            model_name='coursenote',
            index=models.Index(fields=['lesson', 'user'], name='course_note_lesson__b040a8_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresource',
            index=models.Index(fields=['course', 'resource_type'], name='course_reso_course__c39030_idx'),
        ),
    ]
