# Generated by Django 5.0.1 on 2026-07-31 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["user", "-issued_at"], name="idx_cert_user"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["course", "-issued_at"], name="idx_cert_course"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["certificate_code"], name="idx_cert_code"),
        ),
    ]
