# Generated by Django 5.0.1 on 2026-10-01 14:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["user", "-issued_at"], name="idx_cert_user"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["course", "-issued_at"], name="idx_cert_course"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["certificate_code"], name="idx_cert_code"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="course_search_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="lesson_search_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="module",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="module_search_idx"
            ),
        ),
    ]
