# Generated by Django 5.2.10 on 2026-01-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hls_playlist',
            field=models.FileField(blank=True, help_text='Path to master.m3u8', null=True, upload_to='courses/hls/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to='courses/raw_videos/'),
        ),
    ]
