# Generated by Django 5.2.10 on 2026-02-16 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['completed_at'], name='enrollments_complet_ddc915_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['created_at'], name='enrollments_created_52c4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_approved', 'created_at'], name='reviews_is_appr_fce845_idx'),
        ),
    ]
