# Generated by Django 5.0.1 on 2026-03-18 16:43

import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

# Conditional imports for PostgreSQL-only features (pgvector, GIN indexes)
try:
    import django.contrib.postgres.indexes
    import pgvector.django.indexes
    HAS_PGVECTOR = True
except ImportError:
    HAS_PGVECTOR = False


def _build_operations():
    """Build migration operations, skipping PostgreSQL-only indexes on SQLite."""
    ops = [
        migrations.AddField(
            model_name='trackcourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackcourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trackcourse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
    if HAS_PGVECTOR:
        ops.append(
            migrations.AddIndex(
                model_name='course',
                index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'description'], name='course_text_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
            ),
        )
        ops.append(
            migrations.AddIndex(
                model_name='course',
                index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='course_embedding_idx', opclasses=['vector_cosine_ops']),
            ),
        )
    return ops


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_enrollment_enrollments_complet_ddc915_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = _build_operations()
