# Generated by Django 5.0.1 on 2026-04-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_trackcourse_created_at_trackcourse_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lessoncompletion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trackcourse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
