# Generated by Django 5.0.1 on 2026-04-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add database indexes for query performance optimization.
    These indexes improve search, filtering, and ordering operations.
    """

    dependencies = [
        ('courses', '0011_certificate_is_active_course_is_active_and_more'),
    ]

    operations = [
        # Course indexes for search and filtering
        migrations.AddIndex(
            model_name='course',
            index=models.Index(
                fields=['is_published', 'created_at'],
                name='idx_course_published_created',
            ),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(
                fields=['category', 'is_published'],
                name='idx_course_category_published',
            ),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(
                fields=['instructor', 'is_published'],
                name='idx_course_instructor_published',
            ),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(
                fields=['difficulty', 'is_published'],
                name='idx_course_difficulty_published',
            ),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(
                fields=['price', 'is_published'],
                name='idx_course_price_published',
            ),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(
                fields=['avg_rating', 'is_published'],
                name='idx_course_rating_published',
            ),
        ),
        
        # Enrollment indexes for user queries
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(
                fields=['user', 'is_active'],
                name='idx_enrollment_user_active',
            ),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(
                fields=['course', 'created_at'],
                name='idx_enrollment_course_date',
            ),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(
                fields=['user', 'progress_percentage'],
                name='idx_enrollment_user_progress',
            ),
        ),
        
        # Review indexes for rating calculations
        migrations.AddIndex(
            model_name='review',
            index=models.Index(
                fields=['course', 'created_at'],
                name='idx_review_course_date',
            ),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(
                fields=['user', 'created_at'],
                name='idx_review_user_date',
            ),
        ),
        
        # Module and Lesson indexes for course content
        migrations.AddIndex(
            model_name='module',
            index=models.Index(
                fields=['course', 'order'],
                name='idx_module_course_order',
            ),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(
                fields=['module', 'order'],
                name='idx_lesson_module_order',
            ),
        ),
        
        # Certificate indexes for lookups
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(
                fields=['user', 'issued_at'],
                name='idx_cert_user_date',
            ),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(
                fields=['certificate_code'],
                name='idx_cert_code',
            ),
        ),
        
        # Category indexes
        migrations.AddIndex(
            model_name='category',
            index=models.Index(
                fields=['is_active', 'name'],
                name='idx_category_active_name',
            ),
        ),
    ]
