# Generated by Django 5.0.1 on 2026-04-23 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='idx_category_active_name',
        ),
        migrations.RemoveIndex(
            model_name='certificate',
            name='idx_cert_user_date',
        ),
        migrations.RemoveIndex(
            model_name='certificate',
            name='idx_cert_code',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='idx_course_published_created',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='idx_course_category_published',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='idx_course_instructor_published',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='idx_course_difficulty_published',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='idx_course_price_published',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='idx_course_rating_published',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='idx_enrollment_user_active',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='idx_enrollment_course_date',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='idx_enrollment_user_progress',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='idx_lesson_module_order',
        ),
        migrations.RemoveIndex(
            model_name='module',
            name='idx_module_course_order',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='idx_review_course_date',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='idx_review_user_date',
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'course', 'created_at'], name='idx_enroll_usr_crs_date'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['progress_percentage'], name='idx_enrollment_progress'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='idx_review_rating'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_range_1_to_5'),
        ),
    ]
