# Generated by Django 5.0.1 on 2026-04-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_category_idx_category_active_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='lessons_module__1db223_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='course_modu_course__2c6358_idx'),
        ),
        migrations.AlterModelTable(
            name='trackcourse',
            table='track_courses',
        ),
    ]
