# Generated by Django 5.0.1 on 2026-06-08 06:26

import django.contrib.postgres.indexes
import pgvector.django
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_alter_course_options_course_course_pub_created_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="course",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title", "description"],
                name="course_text_search_idx",
                opclasses=["gin_trgm_ops", "gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=pgvector.django.HnswIndex(
                fields=["embedding"],
                name="course_embedding_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
