# Generated by Django 5.0.14 on 2026-09-28 19:00

import apps.updates.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUpdate',
            fields=[
                ('id', models.CharField(default=apps.updates.models.gen_update_id, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('summary', models.TextField()),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('is_ai_summarized', models.BooleanField(default=False)),
                ('source_url', models.URLField(max_length=1000)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('EXAMINATION', 'Examination'), ('ADMISSION', 'Admission'), ('SCHOLARSHIP', 'Scholarship'), ('CAREER', 'Career & Placement'), ('COMPETITIVE_EXAMS', 'Competitive Exams'), ('GENERAL', 'General Announcement')], db_index=True, default='ACADEMIC', max_length=64)),
                ('sub_category', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('institution', models.CharField(db_index=True, max_length=255)),
                ('exam', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('course', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('semester', models.CharField(blank=True, default='', max_length=64)),
                ('session', models.CharField(blank=True, default='', max_length=64)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('REJECTED', 'Rejected')], db_index=True, default='PUBLISHED', max_length=32)),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'Verified Official'), ('PENDING_REVIEW', 'Pending Verification'), ('FLAGGED', 'Flagged / Disputed')], db_index=True, default='VERIFIED', max_length=32)),
                ('importance', models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=32)),
                ('audience', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(default='en', max_length=16)),
                ('related_links', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('last_checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lh_student_updates',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateAttachment',
            fields=[
                ('id', models.CharField(default=apps.updates.models.gen_attachment_id, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=1000)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/pdf', max_length=64)),
                ('sha256_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='updates.studentupdate')),
            ],
            options={
                'db_table': 'lh_update_attachments',
            },
        ),
        migrations.CreateModel(
            name='UpdateCrossLink',
            fields=[
                ('id', models.CharField(default=apps.updates.models.gen_crosslink_id, max_length=64, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('TEST', 'Test A+ Assessment'), ('EBOOK', 'Ebook Chapter'), ('COURSE', 'Course Lesson'), ('STUDY_PLAN', 'Study Planner Goal')], max_length=32)),
                ('target_id', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('action_cta', models.CharField(default='Prepare Now', max_length=64)),
                ('action_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_links', to='updates.studentupdate')),
            ],
            options={
                'db_table': 'lh_update_cross_links',
            },
        ),
        migrations.CreateModel(
            name='UpdateSource',
            fields=[
                ('source_id', models.CharField(default=apps.updates.models.gen_source_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('source_type', models.CharField(choices=[('UNIVERSITY', 'University'), ('EXAM_BOARD', 'Statutory Exam Board'), ('GOVERNMENT', 'Government Education Department'), ('COLLEGE', 'Affiliated College'), ('APPROVED_ORG', 'Approved Organization'), ('SECONDARY', 'Secondary Media Desk')], default='UNIVERSITY', max_length=32)),
                ('authority_level', models.IntegerField(choices=[(1, 'Level 1: Official Authority'), (2, 'Level 2: Institution Controlled Portal'), (3, 'Level 3: Approved Educational Organization'), (4, 'Level 4: Trusted Secondary Source'), (5, 'Level 5: Unverified Community Source')], db_index=True, default=1)),
                ('category', models.CharField(db_index=True, default='ACADEMIC', max_length=64)),
                ('country', models.CharField(default='India', max_length=64)),
                ('state', models.CharField(default='Uttar Pradesh', max_length=64)),
                ('institution', models.CharField(db_index=True, max_length=255)),
                ('base_url', models.URLField(max_length=500)),
                ('fetch_method', models.CharField(choices=[('REST_API', 'Official REST/JSON API'), ('RSS_FEED', 'RSS / Atom Feed'), ('HTML_TABLE', 'Structured HTML Table'), ('DOM_SCRAPE', 'Targeted DOM Extraction'), ('MANUAL', 'Curated Manual Submission')], default='HTML_TABLE', max_length=32)),
                ('polling_interval_minutes', models.IntegerField(default=60)),
                ('robots_policy', models.CharField(default='COMPLIANT', max_length=32)),
                ('terms_status', models.CharField(default='APPROVED', max_length=32)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('verification_required', models.BooleanField(default=False)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lh_update_sources',
                'ordering': ['authority_level', 'name'],
                'indexes': [models.Index(fields=['is_enabled', 'authority_level'], name='lh_update_s_is_enab_fe7e97_idx'), models.Index(fields=['domain'], name='lh_update_s_domain_f3c979_idx')],
            },
        ),
        migrations.CreateModel(
            name='UpdateFetchLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_code', models.IntegerField(default=200)),
                ('latency_ms', models.IntegerField(default=0)),
                ('change_detected', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='updates.updatesource')),
            ],
            options={
                'db_table': 'lh_update_fetch_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studentupdate',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='updates.updatesource'),
        ),
        migrations.CreateModel(
            name='UpdateSourceEndpoint',
            fields=[
                ('id', models.CharField(default=apps.updates.models.gen_endpoint_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('sub_category', models.CharField(default='NOTICE_BOARD', max_length=64)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('css_selector', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='updates.updatesource')),
            ],
            options={
                'db_table': 'lh_update_source_endpoints',
                'ordering': ['source', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UpdateSubscription',
            fields=[
                ('id', models.CharField(default=apps.updates.models.gen_subscription_id, max_length=64, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('INSTITUTION', 'University / Institution'), ('COURSE', 'Degree / Course'), ('SEMESTER', 'Semester'), ('EXAM', 'Competitive Exam'), ('CATEGORY', 'Category')], db_index=True, max_length=32)),
                ('target_value', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lh_update_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='UpdateVersion',
            fields=[
                ('id', models.CharField(default=apps.updates.models.gen_version_id, max_length=64, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('diff_summary', models.TextField(blank=True, default='')),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='updates.studentupdate')),
            ],
            options={
                'db_table': 'lh_update_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='UpdateBookmark',
            fields=[
                ('id', models.CharField(default=apps.updates.models.gen_bookmark_id, max_length=64, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('tag', models.CharField(blank=True, default='General', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='updates.studentupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lh_update_bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'update')},
            },
        ),
        migrations.CreateModel(
            name='UpdateReminder',
            fields=[
                ('id', models.CharField(default=apps.updates.models.gen_reminder_id, max_length=64, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('7_DAYS_BEFORE', '7 Days Before Deadline'), ('3_DAYS_BEFORE', '3 Days Before Deadline'), ('1_DAY_BEFORE', '1 Day Before Deadline'), ('DAY_OF', 'Morning of Deadline Day')], max_length=32)),
                ('trigger_at', models.DateTimeField(db_index=True)),
                ('is_dispatched', models.BooleanField(db_index=True, default=False)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='updates.studentupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lh_update_reminders',
                'indexes': [models.Index(fields=['is_dispatched', 'trigger_at'], name='lh_update_r_is_disp_8955e0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='studentupdate',
            index=models.Index(fields=['category', '-published_at'], name='lh_student__categor_1593cb_idx'),
        ),
        migrations.AddIndex(
            model_name='studentupdate',
            index=models.Index(fields=['institution', 'category'], name='lh_student__institu_479f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentupdate',
            index=models.Index(fields=['status', 'verification_status'], name='lh_student__status_104061_idx'),
        ),
        migrations.AddIndex(
            model_name='studentupdate',
            index=models.Index(fields=['deadline'], name='lh_student__deadlin_d827aa_idx'),
        ),
        migrations.AddIndex(
            model_name='studentupdate',
            index=models.Index(fields=['importance', '-created_at'], name='lh_student__importa_0bffae_idx'),
        ),
        migrations.AddIndex(
            model_name='updatesubscription',
            index=models.Index(fields=['user', 'target_type'], name='lh_update_s_user_id_bf8451_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='updatesubscription',
            unique_together={('user', 'target_type', 'target_value')},
        ),
    ]
