# Generated by Django 5.0.14 on 2026-09-29 16:52

import apps.updates.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateNotificationPreference',
            fields=[
                ('id', models.CharField(default=apps.updates.models.gen_pref_id, max_length=64, primary_key=True, serialize=False)),
                ('quiet_hours_enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(default=datetime.time(22, 0))),
                ('quiet_hours_end', models.TimeField(default=datetime.time(7, 0))),
                ('max_daily_push', models.IntegerField(default=3)),
                ('allow_exam_forms', models.BooleanField(default=True)),
                ('allow_results', models.BooleanField(default=True)),
                ('allow_timetables', models.BooleanField(default=True)),
                ('allow_scholarships', models.BooleanField(default=True)),
                ('allow_admit_cards', models.BooleanField(default=True)),
                ('allow_academic', models.BooleanField(default=True)),
                ('digest_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='update_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lh_update_notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='QueuedUpdateNotification',
            fields=[
                ('id', models.CharField(default=apps.updates.models.gen_queued_id, max_length=64, primary_key=True, serialize=False)),
                ('queue_reason', models.CharField(choices=[('QUIET_HOURS', 'Deferred During Quiet Hours'), ('DIGEST', 'Queued for Daily Digest'), ('RATE_LIMIT', 'Deferred due to Daily Cap')], default='QUIET_HOURS', max_length=32)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('is_dispatched', models.BooleanField(db_index=True, default=False)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_notifications', to='updates.studentupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_update_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lh_queued_update_notifications',
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['is_dispatched', 'scheduled_for'], name='lh_queued_u_is_disp_00dde2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UpdateNotificationAudit',
            fields=[
                ('id', models.CharField(default=apps.updates.models.gen_audit_id, max_length=64, primary_key=True, serialize=False)),
                ('channel', models.CharField(default='IN_APP', max_length=32)),
                ('decision', models.CharField(max_length=32)),
                ('reason', models.CharField(max_length=255)),
                ('delivered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_audits', to='updates.studentupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_notification_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lh_update_notification_audits',
                'ordering': ['-delivered_at'],
                'indexes': [models.Index(fields=['user', '-delivered_at'], name='lh_update_n_user_id_5e1e49_idx')],
            },
        ),
    ]
