# Generated by Django 5.0.14 on 2026-09-29 16:53

import apps.updates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_updatenotificationpreference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultWatcher',
            fields=[
                ('id', models.CharField(default=apps.updates.models.gen_watcher_id, max_length=64, primary_key=True, serialize=False)),
                ('institution', models.CharField(db_index=True, max_length=255)),
                ('course', models.CharField(db_index=True, max_length=255)),
                ('semester', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('roll_number', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Tracking'), ('RESULT_DECLARED', 'Result Declared'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=32)),
                ('result_url', models.URLField(blank=True, default='', max_length=1000)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_watchers', to='updates.studentupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_watchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lh_result_watchers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'institution'], name='lh_result_w_status_390bfd_idx'), models.Index(fields=['user', 'status'], name='lh_result_w_user_id_7bca17_idx')],
            },
        ),
    ]
