# Generated by Django 5.0.14 on 2026-10-01 06:30

import apps.updates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_resultwatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentupdate',
            name='circular_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='studentupdate',
            name='department',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentupdate',
            name='issuer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentupdate',
            name='issuer_role',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='UpdateEngagementLog',
            fields=[
                ('id', models.CharField(default=apps.updates.models.gen_engagement_id, max_length=64, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('IMPRESSION', 'Notice Rendered in Viewport'), ('CLICK_DETAIL', 'Opened Full Detail Page'), ('CLICK_SOURCE', 'Navigated to Official Portal URL'), ('CALENDAR_EXPORT', 'Exported to Google/iCal Calendar'), ('BOOKMARK', 'Saved to Bookmarks'), ('REMINDER_SET', 'Configured Push Reminder')], db_index=True, max_length=32)),
                ('client_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_logs', to='updates.studentupdate')),
            ],
            options={
                'db_table': 'lh_update_engagement_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['update', 'event_type'], name='lh_update_e_update__b2b6a5_idx'), models.Index(fields=['event_type', '-created_at'], name='lh_update_e_event_t_5717e3_idx')],
            },
        ),
    ]
