# Generated by Django 5.0.1 on 2026-08-25 07:14

import apps.ai_tutor.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.CharField(default=apps.ai_tutor.models.generate_ai_msg_id, max_length=64, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('USER', 'User'), ('AI', 'AI Tutor')], default='USER', max_length=10)),
                ('content', models.TextField()),
                ('tokens_used', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lh_ai_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.CharField(default=apps.ai_tutor.models.generate_ai_session_id, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(default='AI Tutor Session', max_length=255)),
                ('context_type', models.CharField(default='GENERAL', max_length=64)),
                ('context_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lh_ai_chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SpacedRepetitionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('repetitions', models.IntegerField(default=0)),
                ('interval_days', models.IntegerField(default=1)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('next_review_date', models.DateField(default=django.utils.timezone.now)),
                ('lapses', models.IntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lh_spaced_repetition_schedules',
            },
        ),
    ]
