# Generated by Django 5.0.1 on 2026-03-18 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0010_trackcourse_created_at_trackcourse_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileWeb3',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(blank=True, help_text='Ethereum/Polygon wallet address (0x...)', max_length=42, null=True, unique=True)),
                ('did', models.CharField(blank=True, help_text='Decentralized Identifier (did:web:...)', max_length=255, null=True, unique=True)),
                ('nonce', models.CharField(blank=True, help_text='Nonce used for cryptographic signature verification during Web3 login.', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web3_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Web3 Profile',
                'verbose_name_plural': 'Web3 Profiles',
                'db_table': 'users_web3_profiles',
            },
        ),
        migrations.CreateModel(
            name='NFTCertificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_id', models.CharField(help_text='Unique Token ID for the NFT', max_length=255, unique=True)),
                ('merkle_root', models.CharField(help_text='Root hash of the Merkle Tree this cert belongs to', max_length=66)),
                ('merkle_proof', models.JSONField(help_text='Path from leaf to root for client-side verification')),
                ('transaction_hash', models.CharField(help_text='Tx Hash where root was anchored on chain', max_length=66)),
                ('metadata_uri', models.URLField(help_text='IPFS or Arweave URI containing the JSON metadata', max_length=500)),
                ('is_revoked', models.BooleanField(default=False, help_text='Can be revoked by admin in case of cheating')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_certificates', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web3_nft_certificates',
                'indexes': [models.Index(fields=['token_id'], name='web3_nft_ce_token_i_afc948_idx'), models.Index(fields=['transaction_hash'], name='web3_nft_ce_transac_41338e_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
