# Generated by Django 5.0.1 on 2026-08-25 07:14

import apps.tests_engine.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(default=apps.tests_engine.models.generate_question_id, max_length=64, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Single Choice MCQ'), ('MULTI_SELECT', 'Multiple Choice'), ('NUMERICAL', 'Numerical Value'), ('SUBJECTIVE', 'Subjective / Essay')], default='MCQ', max_length=32)),
                ('topic', models.CharField(db_index=True, default='General', max_length=100)),
                ('difficulty', models.FloatField(default=0.0)),
                ('discrimination', models.FloatField(default=1.0)),
                ('marks', models.FloatField(default=4.0)),
                ('negative_marks', models.FloatField(default=1.0)),
                ('explanation', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'lh_test_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(default=apps.tests_engine.models.generate_test_id, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(db_index=True, default='DSA', max_length=64)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('total_marks', models.FloatField(default=100.0)),
                ('passing_marks', models.FloatField(default=40.0)),
                ('negative_marking', models.BooleanField(default=True)),
                ('negative_mark_value', models.FloatField(default=1.0)),
                ('is_adaptive', models.BooleanField(default=False)),
                ('max_attempts', models.IntegerField(default=5)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lh_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.CharField(default=apps.tests_engine.models.generate_attempt_id, max_length=64, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('predicted_rank', models.IntegerField(blank=True, null=True)),
                ('irt_ability_theta', models.FloatField(default=0.0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'lh_test_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('correct_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('ability_theta', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lh_topic_performances',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.CharField(default=apps.tests_engine.models.generate_option_id, max_length=64, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tests_engine.question')),
            ],
            options={
                'db_table': 'lh_question_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.CharField(default=apps.tests_engine.models.generate_answer_id, max_length=64, primary_key=True, serialize=False)),
                ('selected_option_ids', models.JSONField(blank=True, default=list)),
                ('text_answer', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.FloatField(default=0.0)),
                ('time_spent_sec', models.IntegerField(default=0)),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_engine.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_engine.question')),
            ],
            options={
                'db_table': 'lh_attempt_answers',
            },
        ),
        migrations.CreateModel(
            name='QuestionBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='tests_engine.question')),
            ],
            options={
                'db_table': 'lh_question_bookmarks',
            },
        ),
    ]
