# Generated by Django 5.0.14 on 2026-09-24 01:44

import apps.tests_engine.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_engine', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attemptanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.CreateModel(
            name='TestSection',
            fields=[
                ('id', models.CharField(default=apps.tests_engine.models.generate_section_id, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=1)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_timed', models.BooleanField(default=False)),
                ('cut_off_marks', models.FloatField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tests_engine.test')),
            ],
            options={
                'db_table': 'lh_test_sections',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='tests_engine.testsection'),
        ),
    ]
