# Generated by Django 5.0.1 on 2026-09-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_engine', '0003_alter_attemptanswer_unique_together_testsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='shuffle_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
    ]
