[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx.err

[program:django]
command=gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 60
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/django.log
stderr_logfile=/var/log/supervisor/django.err
environment=DJANGO_SETTINGS_MODULE="config.settings.production"
