# Generated by Django 5.0.1 on 2026-08-25 07:14

import apps.social.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=apps.social.models.generate_comment_id, max_length=64, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lh_discussion_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.CharField(default=apps.social.models.generate_discussion_id, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(db_index=True, default='General', max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('upvotes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=1)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lh_discussions',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.CharField(default=apps.social.models.generate_live_session_id, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('instructor_name', models.CharField(default='Lead Faculty', max_length=150)),
                ('instructor_avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('topic', models.CharField(default='DSA & System Design', max_length=100)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('meeting_url', models.URLField(blank=True, default='https://meet.learninghub.app/live-session', max_length=500)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live Now'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('attendees_count', models.IntegerField(default=45)),
            ],
            options={
                'db_table': 'lh_live_sessions',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.CharField(default=apps.social.models.generate_mentor_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(default='Senior Software Engineer at Google', max_length=200)),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('specialization', models.CharField(default='DSA, System Design & Interview Prep', max_length=150)),
                ('rating', models.FloatField(default=4.9)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=49.0, max_digits=8)),
                ('available_slots', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'lh_mentors',
            },
        ),
    ]
