# Generated by Django 5.0.1 on 2026-09-07 08:43

import apps.social.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=apps.social.models.generate_notification_id, max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('ACHIEVEMENT', 'Achievement'), ('REMINDER', 'Reminder'), ('SYSTEM', 'System'), ('TEST_RESULT', 'Test Result'), ('COURSE_COMPLETE', 'Course Complete'), ('STREAK', 'Streak'), ('CONTEST_START', 'Contest Start'), ('CONTEST_RESULT', 'Contest Result'), ('SUBSCRIPTION', 'Subscription'), ('LEVEL_UP', 'Level Up')], db_index=True, default='INFO', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('action_url', models.URLField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lh_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='lh_notifica_user_id_35e363_idx'), models.Index(fields=['user', 'type', '-created_at'], name='lh_notifica_user_id_ec9213_idx'), models.Index(fields=['-created_at'], name='lh_notifica_created_75f409_idx')],
            },
        ),
    ]
