# Generated by Django 5.0.1 on 2026-05-05 03:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'quizzes'},
        ),
        migrations.RemoveConstraint(
            model_name='quizattempt',
            name='unique_quiz_attempt',
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('user', 'quiz', 'attempt_number')},
        ),
    ]
