# Generated by Django 5.0.1 on 2026-09-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='streak_freezes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('INSTRUCTOR', 'Instructor'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'Super Admin'), ('MODERATOR', 'Moderator'), ('ENTERPRISE', 'Enterprise')], db_index=True, default='STUDENT', max_length=20),
        ),
    ]
