# Generated by Django 5.2.10 on 2026-01-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
