# Generated by Django 5.0.1 on 2026-01-05 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("title", models.CharField(max_length=200)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("text", "Text Article"),
                            ("pdf", "PDF Document"),
                            ("quiz", "Quiz"),
                        ],
                        max_length=20,
                    ),
                ),
                ("video_url", models.URLField(blank=True)),
                ("video_duration", models.PositiveIntegerField(default=0)),
                ("text_content", models.TextField(blank=True)),
                ("pdf_file", models.FileField(blank=True, upload_to="lessons/pdfs/")),
                ("is_preview", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "lessons",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("watch_time", models.PositiveIntegerField(default=0)),
                ("last_position", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "lesson_progress",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("true_false", "True/False"),
                        ],
                        default="mcq",
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(default=list)),
                ("correct_answer", models.JSONField()),
                ("explanation", models.TextField(blank=True)),
                ("points", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("passing_score", models.PositiveIntegerField(default=70)),
                ("time_limit", models.PositiveIntegerField(null=True)),
            ],
            options={
                "db_table": "quizzes",
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("total_points", models.PositiveIntegerField(default=0)),
                ("passed", models.BooleanField(default=False)),
                ("answers", models.JSONField(default=dict)),
                ("time_taken", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "quiz_attempts",
                "ordering": ["-created_at"],
            },
        ),
    ]
