# Generated by Django 5.0.1 on 2026-06-04 07:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Max discount for percentage type', max_digits=10, null=True)),
                ('max_uses', models.IntegerField(blank=True, help_text='Null = unlimited', null=True)),
                ('uses_per_user', models.IntegerField(default=1)),
                ('current_uses', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('provider_transaction_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('transaction_type', models.CharField(choices=[('subscription_payment', 'Subscription Payment'), ('refund', 'Refund'), ('trial_conversion', 'Trial Conversion'), ('upgrade', 'Plan Upgrade'), ('downgrade', 'Plan Downgrade')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('daily_test_limit', models.IntegerField(default=3, help_text='Tests per day')),
                ('monthly_ai_generations', models.IntegerField(default=5, help_text='AI-generated tests per month')),
                ('max_analytics_depth', models.IntegerField(default=1, help_text='Analytics depth level (1-3)')),
                ('max_bookmarks', models.IntegerField(default=20)),
                ('max_notes', models.IntegerField(default=50)),
                ('features', models.JSONField(default=dict)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('badge_text', models.CharField(blank=True, help_text="e.g., 'Most Popular'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('tests_taken', models.IntegerField(default=0)),
                ('ai_generations', models.IntegerField(default=0)),
                ('minutes_practiced', models.IntegerField(default=0)),
                ('bookmarks_created', models.IntegerField(default=0)),
                ('notes_created', models.IntegerField(default=0)),
                ('peak_concurrent_tests', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'usage_tracking',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('trial', 'Trial'), ('past_due', 'Past Due')], db_index=True, default='active', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_provider', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('paypal', 'PayPal'), ('manual', 'Manual')], max_length=20)),
                ('provider_subscription_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider_customer_id', models.CharField(blank=True, max_length=255)),
                ('last_payment_id', models.CharField(blank=True, max_length=255)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('is_trial', models.BooleanField(default=False)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_subscriptions',
                'ordering': ['-started_at'],
            },
        ),
    ]
