"""
Source Registry Seed Definitions for Official Educational Authorities.
Includes MGKVP, AKTU, Lucknow University, BHU, DDU Gorakhpur, SSC, and NTA.
"""
from typing import List, Dict, Any

SEED_SOURCES: List[Dict[str, Any]] = [
    {
        "source_id": "src-mgkvp-official",
        "name": "Mahatma Gandhi Kashi Vidyapith Main Portal",
        "domain": "mgkvp.ac.in",
        "source_type": "UNIVERSITY",
        "authority_level": 1,
        "category": "ACADEMIC",
        "country": "India",
        "state": "Uttar Pradesh",
        "institution": "Mahatma Gandhi Kashi Vidyapith (MGKVP)",
        "base_url": "https://mgkvp.ac.in",
        "fetch_method": "HTML_TABLE",
        "polling_interval_minutes": 30,
        "robots_policy": "COMPLIANT",
        "terms_status": "APPROVED",
        "is_enabled": True,
        "verification_required": False,
        "endpoints": [
            {
                "id": "ep-mgkvp-notice",
                "name": "General Notice Board",
                "sub_category": "NOTICE_BOARD",
                "endpoint_url": "https://mgkvp.ac.in/Home/NoticeList",
                "css_selector": "table.table-striped tbody tr",
            },
            {
                "id": "ep-mgkvp-exam",
                "name": "Examination & Forms",
                "sub_category": "EXAMINATION",
                "endpoint_url": "https://mgkvp.ac.in/Home/ExamNotices",
                "css_selector": "table.exam-table tr",
            },
            {
                "id": "ep-mgkvp-timetable",
                "name": "Time Table & Centers",
                "sub_category": "TIMETABLE",
                "endpoint_url": "https://mgkvp.ac.in/Home/TimeTable",
                "css_selector": "table.timetable-list tr",
            },
            {
                "id": "ep-mgkvp-results",
                "name": "Evaluation & Results",
                "sub_category": "RESULTS",
                "endpoint_url": "https://mgkvp.ac.in/Home/Results",
                "css_selector": "div.results-panel",
            },
            {
                "id": "ep-mgkvp-admissions",
                "name": "Admissions & Counselling",
                "sub_category": "ADMISSIONS",
                "endpoint_url": "https://mgkvp.ac.in/Home/Admissions",
                "css_selector": "table.admissions-table tr",
            },
        ],
    },
    {
        "source_id": "src-aktu-official",
        "name": "Dr. A.P.J. Abdul Kalam Technical University",
        "domain": "aktu.ac.in",
        "source_type": "UNIVERSITY",
        "authority_level": 1,
        "category": "ACADEMIC",
        "country": "India",
        "state": "Uttar Pradesh",
        "institution": "AKTU Lucknow",
        "base_url": "https://aktu.ac.in",
        "fetch_method": "HTML_TABLE",
        "polling_interval_minutes": 60,
        "robots_policy": "COMPLIANT",
        "terms_status": "APPROVED",
        "is_enabled": True,
        "verification_required": False,
        "endpoints": [
            {
                "id": "ep-aktu-circulars",
                "name": "Circulars & Examination Notices",
                "sub_category": "EXAMINATION",
                "endpoint_url": "https://aktu.ac.in/circulars.html",
                "css_selector": "table.circular-table tr",
            }
        ],
    },
    {
        "source_id": "src-lu-official",
        "name": "University of Lucknow Official Portal",
        "domain": "lkouniv.ac.in",
        "source_type": "UNIVERSITY",
        "authority_level": 1,
        "category": "ACADEMIC",
        "country": "India",
        "state": "Uttar Pradesh",
        "institution": "University of Lucknow",
        "base_url": "https://lkouniv.ac.in",
        "fetch_method": "HTML_TABLE",
        "polling_interval_minutes": 45,
        "robots_policy": "COMPLIANT",
        "terms_status": "APPROVED",
        "is_enabled": True,
        "verification_required": False,
        "endpoints": [
            {
                "id": "ep-lu-notices",
                "name": "Notice Board & Announcements",
                "sub_category": "NOTICE_BOARD",
                "endpoint_url": "https://lkouniv.ac.in/en/page/notices",
                "css_selector": "table.table tr",
            },
            {
                "id": "ep-lu-exams",
                "name": "Examination Schedules & Forms",
                "sub_category": "EXAMINATION",
                "endpoint_url": "https://lkouniv.ac.in/en/page/examination-notices",
                "css_selector": "table.exam-schedule tr",
            },
            {
                "id": "ep-lu-admissions",
                "name": "Admission Notifications & Counselling",
                "sub_category": "ADMISSIONS",
                "endpoint_url": "https://lkouniv.ac.in/en/page/admissions",
                "css_selector": "div.admission-list",
            },
        ],
    },
    {
        "source_id": "src-bhu-official",
        "name": "Banaras Hindu University Official Portal",
        "domain": "bhu.ac.in",
        "source_type": "UNIVERSITY",
        "authority_level": 1,
        "category": "ACADEMIC",
        "country": "India",
        "state": "Uttar Pradesh",
        "institution": "Banaras Hindu University (BHU)",
        "base_url": "https://bhu.ac.in",
        "fetch_method": "HTML_TABLE",
        "polling_interval_minutes": 45,
        "robots_policy": "COMPLIANT",
        "terms_status": "APPROVED",
        "is_enabled": True,
        "verification_required": False,
        "endpoints": [
            {
                "id": "ep-bhu-notices",
                "name": "Central Notice Board",
                "sub_category": "NOTICE_BOARD",
                "endpoint_url": "https://bhu.ac.in/Site/NoticeBoard/",
                "css_selector": "table.notice-table tr",
            },
            {
                "id": "ep-bhu-controller-exams",
                "name": "Office of the Controller of Examinations",
                "sub_category": "EXAMINATION",
                "endpoint_url": "https://bhuonline.in/notices",
                "css_selector": "ul.exam-notices li",
            },
            {
                "id": "ep-bhu-counselling",
                "name": "CUET UG & PG Counseling Portal",
                "sub_category": "ADMISSIONS",
                "endpoint_url": "https://bhuonline.in/counselling",
                "css_selector": "div.counselling-updates",
            },
        ],
    },
    {
        "source_id": "src-ddu-official",
        "name": "Deen Dayal Upadhyaya Gorakhpur University",
        "domain": "ddugu.ac.in",
        "source_type": "UNIVERSITY",
        "authority_level": 1,
        "category": "ACADEMIC",
        "country": "India",
        "state": "Uttar Pradesh",
        "institution": "DDU Gorakhpur University",
        "base_url": "https://ddugu.ac.in",
        "fetch_method": "HTML_TABLE",
        "polling_interval_minutes": 60,
        "robots_policy": "COMPLIANT",
        "terms_status": "APPROVED",
        "is_enabled": True,
        "verification_required": False,
        "endpoints": [
            {
                "id": "ep-ddu-notices",
                "name": "General Notice Board",
                "sub_category": "NOTICE_BOARD",
                "endpoint_url": "https://ddugu.ac.in/Notices.aspx",
                "css_selector": "table#ContentPlaceHolder1_GridView1 tr",
            },
            {
                "id": "ep-ddu-exams",
                "name": "Examination & Time Table Circulars",
                "sub_category": "EXAMINATION",
                "endpoint_url": "https://ddugu.ac.in/ExamNotices.aspx",
                "css_selector": "table#ContentPlaceHolder1_GridViewExam tr",
            },
        ],
    },
    {
        "source_id": "src-uod-official",
        "name": "University of Allahabad Central Portal",
        "domain": "allduniv.ac.in",
        "source_type": "UNIVERSITY",
        "authority_level": 1,
        "category": "ACADEMIC",
        "country": "India",
        "state": "Uttar Pradesh",
        "institution": "University of Allahabad",
        "base_url": "https://allduniv.ac.in",
        "fetch_method": "HTML_TABLE",
        "polling_interval_minutes": 45,
        "robots_policy": "COMPLIANT",
        "terms_status": "APPROVED",
        "is_enabled": True,
        "verification_required": False,
        "endpoints": [
            {
                "id": "ep-uod-notices",
                "name": "General Notice Board & Circulars",
                "sub_category": "NOTICE_BOARD",
                "endpoint_url": "https://allduniv.ac.in/news-events",
                "css_selector": "table.notice-table tr",
            },
            {
                "id": "ep-uod-exams",
                "name": "Examinations & Timetable",
                "sub_category": "EXAMINATION",
                "endpoint_url": "https://allduniv.ac.in/examination",
                "css_selector": "table.exam-table tr",
            },
            {
                "id": "ep-uod-admissions",
                "name": "Admissions & Cutoff Lists",
                "sub_category": "ADMISSIONS",
                "endpoint_url": "https://allduniv.ac.in/admissions",
                "css_selector": "div.admission-block",
            },
        ],
    },
    {
        "source_id": "src-ssc-gov",
        "name": "Staff Selection Commission Official",
        "domain": "ssc.gov.in",
        "source_type": "EXAM_BOARD",
        "authority_level": 1,
        "category": "COMPETITIVE_EXAMS",
        "country": "India",
        "state": "National",
        "institution": "Staff Selection Commission",
        "base_url": "https://ssc.gov.in",
        "fetch_method": "REST_API",
        "polling_interval_minutes": 60,
        "robots_policy": "COMPLIANT",
        "terms_status": "APPROVED",
        "is_enabled": True,
        "verification_required": False,
        "endpoints": [
            {
                "id": "ep-ssc-notices",
                "name": "Latest Announcements",
                "sub_category": "COMPETITIVE_EXAMS",
                "endpoint_url": "https://ssc.gov.in/api/notices",
                "css_selector": "",
            }
        ],
    },
    {
        "source_id": "src-nta-official",
        "name": "National Testing Agency Official Portal",
        "domain": "nta.ac.in",
        "source_type": "EXAM_BOARD",
        "authority_level": 1,
        "category": "COMPETITIVE_EXAMS",
        "country": "India",
        "state": "National",
        "institution": "National Testing Agency (NTA)",
        "base_url": "https://nta.ac.in",
        "fetch_method": "HTML_TABLE",
        "polling_interval_minutes": 30,
        "robots_policy": "COMPLIANT",
        "terms_status": "APPROVED",
        "is_enabled": True,
        "verification_required": False,
        "endpoints": [
            {
                "id": "ep-nta-public-notices",
                "name": "Public Notices & Press Releases",
                "sub_category": "COMPETITIVE_EXAMS",
                "endpoint_url": "https://nta.ac.in/NoticeArchive",
                "css_selector": "table.table tr",
            },
            {
                "id": "ep-nta-cuet",
                "name": "Common University Entrance Test (CUET)",
                "sub_category": "ADMISSIONS",
                "endpoint_url": "https://exams.nta.ac.in/CUET-UG/",
                "css_selector": "div.notice-board",
            },
            {
                "id": "ep-nta-jee",
                "name": "JEE Main Official Portal",
                "sub_category": "COMPETITIVE_EXAMS",
                "endpoint_url": "https://jeemain.nta.ac.in/",
                "css_selector": "div.public-notice",
            },
            {
                "id": "ep-nta-neet",
                "name": "NEET UG Official Portal",
                "sub_category": "COMPETITIVE_EXAMS",
                "endpoint_url": "https://neet.nta.nic.in/",
                "css_selector": "div.news-events",
            },
        ],
    },
]
