# Generated by Django 5.0.14 on 2026-09-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_certificate_course_instructor_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='negative_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='passing_score',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='course',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
    ]
