import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding Tests A+ Data...')

  // 1. Seed Countries
  const uk = await prisma.country.upsert({
    where: { code: 'GB' },
    update: {},
    create: { code: 'GB', name: 'United Kingdom', flagEmoji: '🇬🇧' },
  })

  const us = await prisma.country.upsert({
    where: { code: 'US' },
    update: {},
    create: { code: 'US', name: 'United States', flagEmoji: '🇺🇸' },
  })

  const india = await prisma.country.upsert({
    where: { code: 'IN' },
    update: {},
    create: { code: 'IN', name: 'India', flagEmoji: '🇮🇳' },
  })

  // 2. Seed Exams
  const gcse = await prisma.exam.upsert({
    where: { slug: 'gcse' },
    update: {},
    create: {
      countryId: uk.id,
      name: 'GCSE',
      slug: 'gcse',
      description: 'General Certificate of Secondary Education',
    },
  })

  const aLevel = await prisma.exam.upsert({
    where: { slug: 'a-level' },
    update: {},
    create: {
      countryId: uk.id,
      name: 'A-Level',
      slug: 'a-level',
      description: 'Advanced Level Qualifications',
    },
  })

  const sat = await prisma.exam.upsert({
    where: { slug: 'sat' },
    update: {},
    create: {
      countryId: us.id,
      name: 'SAT',
      slug: 'sat',
      description: 'Scholastic Assessment Test',
    },
  })

  const jee = await prisma.exam.upsert({
    where: { slug: 'jee-mains' },
    update: {},
    create: {
      countryId: india.id,
      name: 'JEE Mains',
      slug: 'jee-mains',
      description: 'Joint Entrance Examination',
    },
  })

  const neet = await prisma.exam.upsert({
    where: { slug: 'neet' },
    update: {},
    create: {
      countryId: india.id,
      name: 'NEET',
      slug: 'neet',
      description: 'National Eligibility cum Entrance Test',
    },
  })

  // 3. Seed Subjects for A-Level
  const mathALevel = await prisma.subject.upsert({
    where: { slug: 'a-level-mathematics' },
    update: {},
    create: {
      examId: aLevel.id,
      name: 'Mathematics',
      slug: 'a-level-mathematics',
      topics: {
        create: [
          { name: 'Pure Mathematics', slug: 'pure-mathematics' },
          { name: 'Mechanics', slug: 'mechanics' },
          { name: 'Statistics', slug: 'statistics' }
        ]
      },
    },
  })

  const physicsALevel = await prisma.subject.upsert({
    where: { slug: 'a-level-physics' },
    update: {},
    create: {
      examId: aLevel.id,
      name: 'Physics',
      slug: 'a-level-physics',
      topics: {
        create: [
          { name: 'Mechanics', slug: 'physics-mechanics' },
          { name: 'Waves', slug: 'waves' },
          { name: 'Electricity', slug: 'electricity' },
          { name: 'Quantum Physics', slug: 'quantum-physics' }
        ]
      },
    },
  })

  // 4. Seed PYQs (Previous Year Questions) for A-Level Math
  await prisma.pYQ.upsert({
    where: {
      id: 'mock-pyq-1' // using deterministic string for idempotency if it wasn't autogenerated, wait id is uuid.
      // We will skip upserting PYQ and use create if not exists by checking count
    },
    update: {},
    create: {
      id: 'mock-pyq-1',
      examType: 'A_LEVEL',
      examId: aLevel.id,
      subjectId: mathALevel.id,
      year: 2023,
      paper: 'Paper 1: Pure Mathematics',
      question: 'Find the derivative of $f(x) = x^3 - 4x^2 + 5x - 2$.',
      marks: 3,
      tags: ['Calculus', 'Differentiation'],
      answer: '$f\'(x) = 3x^2 - 8x + 5$',
      explanation: 'Use power rule on each term separately.',
      difficulty: 'MEDIUM',
    }
  }).catch(() => console.log('Mock PYQ 1 exists'))

  await prisma.pYQ.upsert({
    where: { id: 'mock-pyq-2' },
    update: {},
    create: {
      id: 'mock-pyq-2',
      examType: 'A_LEVEL',
      examId: aLevel.id,
      subjectId: mathALevel.id,
      year: 2023,
      paper: 'Paper 1: Pure Mathematics',
      question: 'Solve the equation $\\sin(2x) = 0.5$ for $0 \\le x \\le 180^\\circ$.',
      marks: 4,
      tags: ['Trigonometry', 'Equations'],
      answer: '$2x = 30^\\circ, 150^\\circ, 390^\\circ, 510^\\circ \\implies x = 15^\\circ, 75^\\circ$',
      explanation: 'Detailed steps...',
      difficulty: 'HARD',
    }
  }).catch(() => console.log('Mock PYQ 2 exists'))

  const physicsJEE = await prisma.subject.upsert({
    where: { slug: 'jee-physics' },
    update: {},
    create: { examId: jee.id, name: 'Physics', slug: 'jee-physics' }
  })

  // 5. Seed PYQs (Previous Year Questions) for JEE Mains Physics
  const jeePhysicsQuestions = [
    {
      id: 'mock-jee-1',
      question: 'A particle moves along the x-axis from x=0 to x=5m under the influence of a force given by F = 7 - 2x + 3x^2. The work done in the process is:',
      options: ['135 J', '235 J', '85 J', '15 J'],
      correctOption: '135 J',
      explanation: 'Work done W = \\int F dx = \\int_0^5 (7 - 2x + 3x^2) dx = [7x - x^2 + x^3]_0^5 = 35 - 25 + 125 = 135 J.',
      difficulty: 'MEDIUM',
      tags: ['Work, Energy and Power', 'Integration'],
    },
    {
      id: 'mock-jee-2',
      question: 'Two coherent point sources S1 and S2 are separated by a small distance d. The fringes obtained on the screen will be:',
      options: ['Straight lines', 'Concentric circles', 'Hyperbolas', 'Parabolas'],
      correctOption: 'Hyperbolas',
      explanation: 'For two coherent point sources, the locus of points with a constant path difference is a hyperbola.',
      difficulty: 'HARD',
      tags: ['Wave Optics', 'Interference'],
    },
    {
      id: 'mock-jee-3',
      question: 'The half-life of a radioactive substance is 20 minutes. The approximate time interval (t2 - t1) between the time t2 when 2/3 of it has decayed and time t1 when 1/3 of it had decayed is:',
      options: ['20 min', '28 min', '14 min', '7 min'],
      correctOption: '20 min',
      explanation: 'Time t1 for 1/3 decay means 2/3 remains. Time t2 for 2/3 decay means 1/3 remains. The remaining amount goes from 2/3 to 1/3, which is exactly half of what was present at t1. Thus, t2 - t1 is one half-life, which is 20 minutes.',
      difficulty: 'MEDIUM',
      tags: ['Modern Physics', 'Radioactivity'],
    }
  ]

  for (const q of jeePhysicsQuestions) {
    await prisma.pYQ.upsert({
      where: { id: q.id },
      update: {},
      create: {
        id: q.id,
        examType: 'JEE_MAINS',
        examId: jee.id,
        subjectId: physicsJEE.id,
        year: 2023,
        paper: 'JEE Main 2023 Shift 1',
        question: q.question,
        marks: 4,
        tags: q.tags,
        answer: q.correctOption,
        explanation: q.explanation,
        difficulty: q.difficulty,
      }
    }).catch(() => console.log(`${q.id} exists`))
  }

  const bioNEET = await prisma.subject.upsert({
    where: { slug: 'neet-biology' },
    update: {},
    create: { examId: neet.id, name: 'Biology', slug: 'neet-biology' }
  })

  // 6. Seed PYQs for NEET Biology
  const neetBioQuestions = [
    {
      id: 'mock-neet-1',
      question: 'Which of the following represents the correct sequence of phases in the cell cycle?',
      options: ['G1 -> S -> G2 -> M', 'G1 -> G2 -> S -> M', 'M -> G1 -> G2 -> S', 'S -> G1 -> G2 -> M'],
      correctOption: 'G1 -> S -> G2 -> M',
      explanation: 'The correct sequence of the cell cycle is G1 (Gap 1), S (Synthesis), G2 (Gap 2), and M (Mitosis).',
      difficulty: 'EASY',
      tags: ['Cell Cycle', 'Cell Division'],
    },
    {
      id: 'mock-neet-2',
      question: 'The term "Linkage" was coined by:',
      options: ['G. Mendel', 'W. Bateson', 'T.H. Morgan', 'T. Boveri'],
      correctOption: 'T.H. Morgan',
      explanation: 'The term linkage was coined by T.H. Morgan to describe the physical association of genes on a chromosome.',
      difficulty: 'EASY',
      tags: ['Genetics', 'Principles of Inheritance'],
    },
    {
      id: 'mock-neet-3',
      question: 'In a standard ECG, which of the following alphabets is the correct representation of the respective activity of the human heart?',
      options: ['S - start of systole', 'T - end of diastole', 'P - depolarisation of the atria', 'R - repolarisation of ventricles'],
      correctOption: 'P - depolarisation of the atria',
      explanation: 'In a standard ECG, the P wave represents the electrical excitation (or depolarisation) of the atria.',
      difficulty: 'MEDIUM',
      tags: ['Human Physiology', 'Body Fluids and Circulation'],
    }
  ]

  for (const q of neetBioQuestions) {
    await prisma.pYQ.upsert({
      where: { id: q.id },
      update: {},
      create: {
        id: q.id,
        examType: 'NEET',
        examId: neet.id,
        subjectId: bioNEET.id,
        year: 2023,
        paper: 'NEET 2023',
        question: q.question,
        marks: 4,
        tags: q.tags,
        answer: q.correctOption,
        explanation: q.explanation,
        difficulty: q.difficulty,
      }
    }).catch(() => console.log(`${q.id} exists`))
  }

  console.log('✅ Tests A+ Data Seeding Complete!')
}

main()
  .catch(e => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
