# Generated by Django 5.0.1 on 2026-04-19 11:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.CharField(max_length=50)),
                ('resource', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('details', models.TextField(blank=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx'), models.Index(fields=['actor'], name='core_auditl_actor_i_870709_idx'), models.Index(fields=['severity', 'created_at'], name='core_auditl_severit_c1f910_idx'), models.Index(fields=['ip_address'], name='core_auditl_ip_addr_d66782_idx')],
            },
        ),
    ]
