# Generated by Django 5.0.1 on 2026-05-03 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('severity', models.CharField(default='info', max_length=20)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('execution_time_ms', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('stack_trace', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'enterprise_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='enterprise__user_id_1941b9_idx'), models.Index(fields=['action', 'created_at'], name='enterprise__action_40b190_idx'), models.Index(fields=['resource_type', 'resource_id'], name='enterprise__resourc_61f533_idx'), models.Index(fields=['severity', 'created_at'], name='enterprise__severit_91c84f_idx')],
            },
        ),
    ]
