# Generated by Django 5.0.1 on 2026-06-04 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='enterpriseauditlog',
            index=models.Index(fields=['user_id', 'created_at'], name='enterprise__user_id_1941b9_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseauditlog',
            index=models.Index(fields=['action', 'created_at'], name='enterprise__action_40b190_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseauditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='enterprise__resourc_61f533_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseauditlog',
            index=models.Index(fields=['severity', 'created_at'], name='enterprise__severit_91c84f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor'], name='core_auditl_actor_i_870709_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'created_at'], name='core_auditl_severit_c1f910_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address'], name='core_auditl_ip_addr_d66782_idx'),
        ),
    ]
