# Generated by Django 5.0.1 on 2026-07-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="auditlog_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="auditlog_active_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="auditlog_recent_idx",
        ),
        migrations.RemoveIndex(
            model_name="enterpriseauditlog",
            name="entaudit_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="enterpriseauditlog",
            name="entaudit_active_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="enterpriseauditlog",
            name="entaudit_username_idx",
        ),
        migrations.RemoveIndex(
            model_name="enterpriseauditlog",
            name="entaudit_resource_idx",
        ),
    ]
