# Generated by Django 5.0.1 on 2026-03-18 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0010_trackcourse_created_at_trackcourse_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mesh_url', models.URLField(blank=True, help_text='ReadyPlayerMe or custom GLB avatar', max_length=500, null=True)),
                ('last_x', models.FloatField(default=0.0)),
                ('last_y', models.FloatField(default=0.0)),
                ('last_z', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metaverse_avatar_states',
            },
        ),
        migrations.CreateModel(
            name='MetaverseRoom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_slug', models.SlugField(help_text='Unique identifier for the WebRTC/WebSocket channel', max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Is this room currently open for students?')),
                ('max_capacity', models.PositiveIntegerField(default=50, help_text='Maximum number of simultaneous avatars')),
                ('environment_asset_url', models.URLField(blank=True, help_text='URL to the glTF/GLB 3D scene file', max_length=500, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metaverse_rooms', to='courses.course')),
            ],
            options={
                'verbose_name': 'Metaverse Room',
                'verbose_name_plural': 'Metaverse Rooms',
                'db_table': 'metaverse_rooms',
            },
        ),
    ]
