# Generated by Django 5.0.1 on 2026-04-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarstate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
