# Generated by Django 5.0.1 on 2026-04-14 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='feedback',
            name='ai_suggested_response',
            field=models.TextField(blank=True, help_text='Auto-generated triage answer.'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='urgency_score',
            field=models.IntegerField(default=1, help_text='1 (Low) to 10 (Critical) calculated by AI.'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status', '-created_at'], name='feedback_status_711338_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['user', 'status'], name='feedback_user_id_6a3e47_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['urgency_score', 'status'], name='feedback_urgency_c1d61f_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['category'], name='feedback_categor_2a8dde_idx'),
        ),
    ]
