# Generated by Django 5.0.1 on 2026-05-15 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('practice_topic', 'Practice specific topic'), ('retake_test', 'Retake a test'), ('study_resource', 'Study resource suggestion'), ('difficulty_adjust', 'Adjust difficulty level'), ('focus_area', 'Focus on weak area'), ('milestone', 'Milestone achievement'), ('motivation', 'Motivational message')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_topic_id', models.UUIDField(blank=True, null=True)),
                ('target_test_id', models.UUIDField(blank=True, null=True)),
                ('target_exam_id', models.UUIDField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_actioned', models.BooleanField(default=False)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('reasoning', models.TextField(blank=True, help_text='AI reasoning for this recommendation')),
                ('confidence', models.FloatField(default=0.5, help_text='AI confidence (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_recommendations',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_actioned', 'is_dismissed'], name='ai_recommen_user_id_3721da_idx'), models.Index(fields=['priority'], name='ai_recommen_priorit_9019d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_tests_taken', models.IntegerField(default=0)),
                ('total_questions_answered', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('avg_percentage', models.FloatField(default=0)),
                ('best_percentage', models.FloatField(default=0)),
                ('worst_percentage', models.FloatField(default=100)),
                ('latest_percentage', models.FloatField(default=0)),
                ('percentile_rank', models.FloatField(blank=True, help_text='Percentile vs other users (0-100)', null=True)),
                ('weak_topics', models.JSONField(default=list, help_text='Topic IDs with accuracy < 40%')),
                ('strong_topics', models.JSONField(default=list, help_text='Topic IDs with accuracy > 80%')),
                ('avg_time_per_question', models.FloatField(default=0)),
                ('first_test_date', models.DateTimeField(blank=True, null=True)),
                ('last_test_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_performances', to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_performances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_performance',
                'indexes': [models.Index(fields=['user', 'avg_percentage'], name='exam_perfor_user_id_56534a_idx'), models.Index(fields=['exam', 'avg_percentage'], name='exam_perfor_exam_id_6baadb_idx')],
                'unique_together': {('user', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('tests_taken', models.IntegerField(default=0)),
                ('avg_percentage', models.FloatField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_time_minutes', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_trends',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='performance_user_id_6c1b22_idx'), models.Index(fields=['user', 'exam', 'date'], name='performance_user_id_7527e7_idx')],
                'unique_together': {('user', 'exam', 'date', 'period')},
            },
        ),
        migrations.CreateModel(
            name='TopicPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('incorrect_attempts', models.IntegerField(default=0)),
                ('unanswered_attempts', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0, help_text='Correct / Total (0-100)')),
                ('total_time_seconds', models.IntegerField(default=0)),
                ('avg_time_seconds', models.FloatField(default=0)),
                ('fastest_time_seconds', models.IntegerField(default=0)),
                ('slowest_time_seconds', models.IntegerField(default=0)),
                ('last_5_accuracy', models.FloatField(default=0, help_text='Accuracy of last 5 attempts')),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining'), ('new', 'No data yet')], default='stable', max_length=15)),
                ('mastery_level', models.FloatField(default=0, help_text='Mastery score (0-100)')),
                ('last_attempted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_performances', to='exams.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_performances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'topic_performance',
                'indexes': [models.Index(fields=['user', 'accuracy'], name='topic_perfo_user_id_4d55a2_idx'), models.Index(fields=['user', 'mastery_level'], name='topic_perfo_user_id_c584f3_idx'), models.Index(fields=['user', 'trend'], name='topic_perfo_user_id_01e36d_idx'), models.Index(fields=['topic', 'accuracy'], name='topic_perfo_topic_i_b25519_idx')],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
