# Generated by Django 5.0.1 on 2026-06-04 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_v2', '0001_initial'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examperformance',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_performances', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examperformance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_performances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancetrend',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam'),
        ),
        migrations.AddField(
            model_name='performancetrend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_trends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topicperformance',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_performances', to='exams.topic'),
        ),
        migrations.AddField(
            model_name='topicperformance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_performances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['user', 'is_actioned', 'is_dismissed'], name='ai_recommen_user_id_3721da_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['priority'], name='ai_recommen_priorit_9019d1_idx'),
        ),
        migrations.AddIndex(
            model_name='examperformance',
            index=models.Index(fields=['user', 'avg_percentage'], name='exam_perfor_user_id_56534a_idx'),
        ),
        migrations.AddIndex(
            model_name='examperformance',
            index=models.Index(fields=['exam', 'avg_percentage'], name='exam_perfor_exam_id_6baadb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examperformance',
            unique_together={('user', 'exam')},
        ),
        migrations.AddIndex(
            model_name='performancetrend',
            index=models.Index(fields=['user', 'date'], name='performance_user_id_6c1b22_idx'),
        ),
        migrations.AddIndex(
            model_name='performancetrend',
            index=models.Index(fields=['user', 'exam', 'date'], name='performance_user_id_7527e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancetrend',
            unique_together={('user', 'exam', 'date', 'period')},
        ),
        migrations.AddIndex(
            model_name='topicperformance',
            index=models.Index(fields=['user', 'accuracy'], name='topic_perfo_user_id_4d55a2_idx'),
        ),
        migrations.AddIndex(
            model_name='topicperformance',
            index=models.Index(fields=['user', 'mastery_level'], name='topic_perfo_user_id_c584f3_idx'),
        ),
        migrations.AddIndex(
            model_name='topicperformance',
            index=models.Index(fields=['user', 'trend'], name='topic_perfo_user_id_01e36d_idx'),
        ),
        migrations.AddIndex(
            model_name='topicperformance',
            index=models.Index(fields=['topic', 'accuracy'], name='topic_perfo_topic_i_b25519_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicperformance',
            unique_together={('user', 'topic')},
        ),
    ]
