# Generated by Django 5.0.1 on 2026-08-25 07:14

import apps.problems.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.CharField(default=apps.problems.models.generate_problem_id, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], db_index=True, default='Medium', max_length=16)),
                ('category', models.CharField(db_index=True, default='Algorithms', max_length=64)),
                ('acceptance_rate', models.FloatField(default=68.5)),
                ('submissions_count', models.IntegerField(default=2450)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('starter_code', models.JSONField(blank=True, default=dict)),
                ('time_limit_sec', models.FloatField(default=2.0)),
                ('memory_limit_mb', models.IntegerField(default=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lh_problems',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'lh_problem_testcases',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProblemSubmission',
            fields=[
                ('id', models.CharField(default=apps.problems.models.generate_submission_id, max_length=64, primary_key=True, serialize=False)),
                ('language', models.CharField(default='python', max_length=32)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Runtime Error', 'Runtime Error'), ('Compilation Error', 'Compilation Error')], default='Accepted', max_length=32)),
                ('runtime_ms', models.IntegerField(default=45)),
                ('memory_mb', models.FloatField(default=14.2)),
                ('passed_testcases', models.IntegerField(default=0)),
                ('total_testcases', models.IntegerField(default=0)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
            ],
            options={
                'db_table': 'lh_problem_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
