# Generated by Django 5.0.1 on 2026-09-07 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('AUTH_LOGIN_SUCCESS', 'Auth: Login Success'), ('AUTH_LOGIN_FAILED', 'Auth: Login Failed'), ('AUTH_ACCOUNT_LOCKED', 'Auth: Account Locked'), ('AUTH_PASSWORD_CHANGE', 'Auth: Password Change'), ('AUTH_MFA_ENABLED', 'Auth: MFA Enabled'), ('AUTH_LOGOUT', 'Auth: Logout'), ('RBAC_ROLE_CHANGE', 'RBAC: Role Changed'), ('USER_DEACTIVATED', 'User: Deactivated / Banned'), ('COMMERCE_ORDER_PAID', 'Commerce: Order Paid'), ('COMMERCE_REFUND', 'Commerce: Order Refunded'), ('ACADEMIC_GRADE_OVERRIDE', 'Academic: Grade Overridden'), ('TEST_SUBMITTED', 'Test: Submitted'), ('CERTIFICATE_ISSUED', 'Certificate: Issued'), ('PROCTORING_VIOLATION', 'Proctoring: Violation Logged'), ('SECURITY_ALERT', 'Security: Alert Triggered'), ('CODE_SUBMISSION', 'DSA: Code Submitted')], db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('entry_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lh_audit_logs',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='lh_audit_lo_action_df5568_idx'), models.Index(fields=['actor', 'created_at'], name='lh_audit_lo_actor_i_b4473b_idx')],
            },
        ),
    ]
