# Generated by Django 5.0.1 on 2026-04-14 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionreply',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discussionreply',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent reply for nested threaded discussions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_replies', to='discussions.discussionreply'),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discussionvote',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='threadtag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
