# Generated by Django 5.0.1 on 2026-04-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_discussionreply_is_active_discussionreply_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionvote',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
