# Generated by Django 5.0.1 on 2026-07-04 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_performance_indexes'),
        ('discussions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='discussionreply',
            index=models.Index(fields=['author', '-created_at'], name='idx_reply_author'),
        ),
        migrations.AddIndex(
            model_name='discussionreply',
            index=models.Index(fields=['thread', 'is_accepted_answer'], name='idx_reply_accepted'),
        ),
        migrations.AddIndex(
            model_name='discussionreply',
            index=models.Index(fields=['parent', 'created_at'], name='idx_reply_nested'),
        ),
        migrations.AddIndex(
            model_name='discussionreply',
            index=models.Index(fields=['-like_count'], name='idx_reply_likes'),
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['is_pinned', '-created_at'], name='idx_thread_pinned'),
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['is_resolved', '-created_at'], name='idx_thread_resolved'),
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['-like_count'], name='idx_thread_likes'),
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['-views'], name='idx_thread_views'),
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['course', 'is_resolved', '-created_at'], name='idx_thread_course_status'),
        ),
        migrations.AddIndex(
            model_name='threadtag',
            index=models.Index(fields=['name'], name='idx_tag_name'),
        ),
    ]
