# Generated by Django 5.0.1 on 2026-10-01 14:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_add_search_vector"),
        ("discussions", "0003_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="discussionthread",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="discussionthread",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="discussion_search_idx"
            ),
        ),
    ]
