# Generated by Django 5.0.1 on 2026-04-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add database indexes for user model query performance optimization.
    """

    dependencies = [
        ('users', '0003_organization_is_active_organizationmember_is_active_and_more'),
    ]

    operations = [
        # User indexes for search and filtering
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['is_active', 'created_at'],
                name='idx_user_active_created',
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['role', 'is_active'],
                name='idx_user_role_active',
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['is_verified', 'is_active'],
                name='idx_user_verified_active',
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['last_login'],
                name='idx_user_last_login',
            ),
        ),
        
        # Organization indexes
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(
                fields=['is_active', 'name'],
                name='idx_org_active_name',
            ),
        ),
        
        # OrganizationMember indexes
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(
                fields=['user', 'role'],
                name='idx_orgmember_user_role',
            ),
        ),
    ]
