# Generated by Django 5.0.1 on 2026-04-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organization',
            name='idx_org_active_name',
        ),
        migrations.RemoveIndex(
            model_name='organizationmember',
            name='idx_orgmember_user_role',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_active_created',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_role_active',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_verified_active',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_last_login',
        ),
    ]
