# Generated by Django 5.0.1 on 2026-05-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_course_options_course_course_pub_created_idx_and_more'),
        ('users', '0012_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bookmark', 'verbose_name_plural': 'Bookmarks'},
        ),
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='unique_user_course_bookmark',
        ),
        migrations.RenameIndex(
            model_name='bookmark',
            new_name='user_bookma_user_id_2928de_idx',
            old_name='user_bookmarks_user_id_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='bookmark',
            new_name='user_bookma_course__652800_idx',
            old_name='user_bookmarks_course_id_idx',
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'course')},
        ),
    ]
