"""
Hypernetwork Engine (Phase 89).
Networks generating weights for other networks based on contextual variables.
"""
import math
import random
import logging
from typing import List, Dict, Any, Tuple

logger = logging.getLogger(__name__)


def relu(x: float) -> float:
    return max(0.0, x)


class TargetNetwork:
    """
    Phase 89: The Primary/Target Network.
    Its weights are NOT learned directly via gradient descent.
    Its weights are GENERATED dynamically by the Hypernetwork.
    """
    def __init__(self, in_features: int, out_features: int):
        self.in_features = in_features
        self.out_features = out_features
        # Weights will be populated dynamically
        self.weights = []
        self.bias = []
        
    def load_weights(self, generated_vector: List[float]):
        """Unpacks a flat vector generated by the Hypernetwork into weights and biases."""
        expected_size = (self.in_features * self.out_features) + self.out_features
        if len(generated_vector) != expected_size:
            raise ValueError("Size mismatch for generated weights.")
            
        w_end = self.in_features * self.out_features
        w_flat = generated_vector[:w_end]
        
        # Reshape to matrix
        self.weights = []
        idx = 0
        for _ in range(self.out_features):
            row = []
            for _ in range(self.in_features):
                row.append(w_flat[idx])
                idx += 1
            self.weights.append(row)
            
        self.bias = generated_vector[w_end:]
        
    def forward(self, x: List[float]) -> List[float]:
        if not self.weights or not self.bias:
            raise RuntimeError("Primary weights not loaded from Hypernetwork.")
            
        out = []
        for i in range(self.out_features):
            val = sum(x[j] * self.weights[i][j] for j in range(self.in_features)) + self.bias[i]
            out.append(relu(val))
        return out


class HypernetworkEngine:
    """
    Phase 89: Hypernetwork.
    Takes context (e.g., student metadata, course domain) and generates
    the raw weight matrices for the Primary Network on the fly.
    """
    def __init__(self, context_dim: int, target_in_dim: int, target_out_dim: int, hidden_dim: int = 16):
        self.context_dim = context_dim
        # The output of the hypernetwork must exactly equal the number of parameters in the target network
        self.output_dim = (target_in_dim * target_out_dim) + target_out_dim
        
        self.hidden_dim = hidden_dim
        
        # Hypernetwork weights (these are the ONLY parameters learned via backprop)
        scale1 = math.sqrt(2.0 / (context_dim + hidden_dim))
        self.W1 = [[random.gauss(0, scale1) for _ in range(hidden_dim)] for _ in range(context_dim)]
        self.B1 = [0.0] * hidden_dim
        
        scale2 = math.sqrt(2.0 / (hidden_dim + self.output_dim))
        self.W2 = [[random.gauss(0, scale2) for _ in range(self.output_dim)] for _ in range(hidden_dim)]
        self.B2 = [0.0] * self.output_dim
        
        # The Target network instance
        self.target_net = TargetNetwork(target_in_dim, target_out_dim)

    def generate_weights(self, context_vector: List[float]) -> List[float]:
        """Forward pass of Hypernetwork to output flat weight vector"""
        # H1
        h1 = [sum(context_vector[i] * self.W1[i][j] for i in range(self.context_dim)) + self.B1[j] for j in range(self.hidden_dim)]
        h1_relu = [relu(x) for x in h1]
        
        # H2 / Output parameters
        out = [sum(h1_relu[i] * self.W2[i][j] for i in range(self.hidden_dim)) + self.B2[j] for j in range(self.output_dim)]
        return out

    def forward_target(self, context_vector: List[float], input_features: List[float]) -> List[float]:
        """Full end-to-end forward pass"""
        # 1. Generate weights dynamically based on context
        generated_weights = self.generate_weights(context_vector)
        
        # 2. Inject weights into target network
        self.target_net.load_weights(generated_weights)
        
        # 3. Process primary input through target network
        return self.target_net.forward(input_features)
