"""
Inverse Reinforcement Learning (IRL) Engine (Phase 110).
Apprenticeship Learning: Extracting a continuous reward function from expert demonstrations.
"""
import random
import math
import logging
from typing import Dict, Any, List

logger = logging.getLogger(__name__)


class IRLEngine:
    """
    Simulates MaxEnt Inverse Reinforcement Learning.
    Instead of finding a policy given a reward function (Standard RL),
    IRL attempts to find the underlying reward function given an expert's policy/trajectory.
    """
    def __init__(self, state_features_dim: int = 5):
        self.feature_dim = state_features_dim
        
        # The unknown reward function we are trying to learn: R(s) = w^T * f(s)
        self.learned_reward_weights = [random.gauss(0, 0.1) for _ in range(self.feature_dim)]
        
        self.learning_rate = 0.05
        
    def _extract_state_features(self, state: List[float]) -> List[float]:
        # Simulating some feature mapping phi(s)
        return [abs(s) for s in state] # e.g. distance from target

    def learn_from_expert(self, num_iterations: int = 20) -> Dict[str, Any]:
        """
        Simulates the extraction of reward weights.
        1. Calculate Expert's Feature Expectation.
        2. Calculate Learner's Feature Expectation (given current reward estimate).
        3. Gradient Ascent to match Expert features.
        """
        # 1. Simulate Expert Demonstrations
        num_expert_trajectories = 10
        traj_len = 15
        
        expert_feature_expectation = [0.0] * self.feature_dim
        
        for _ in range(num_expert_trajectories):
            gamma_t = 1.0
            for t in range(traj_len):
                # Expert stays close to origin (simulating a balance task)
                expert_state = [random.gauss(0, 0.1) for _ in range(self.feature_dim)]
                features = self._extract_state_features(expert_state)
                
                for f in range(self.feature_dim):
                    expert_feature_expectation[f] += gamma_t * features[f]
                
                gamma_t *= 0.99
                
        # Normalize
        expert_feature_expectation = [val / num_expert_trajectories for val in expert_feature_expectation]
        
        # 2. Iterative Learning (MaxEnt IRL gradient)
        # Grad L(w) = Expert_Features - Expected_Features_of_optimal_policy_under_w
        
        weight_history = []
        feature_diff_history = []
        
        for iteration in range(num_iterations):
            # Step A: Solve the MDP given current weight estimates.
            # (We simulate the resulting policy's feature expectation)
            learner_feature_expectation = [0.0] * self.feature_dim
            gamma_t = 1.0
            
            # The learner policy is dictated by the current weights
            for t in range(traj_len):
                # Simulate a state generated by the current flawed policy
                # If weight is high, it tries to minimize that feature (if negative reward)
                learner_state = [
                    random.gauss(0, 0.5) * math.exp(-self.learned_reward_weights[f]) 
                    for f in range(self.feature_dim)
                ]
                
                features = self._extract_state_features(learner_state)
                for f in range(self.feature_dim):
                    learner_feature_expectation[f] += gamma_t * features[f]
                gamma_t *= 0.99
                
            learner_feature_expectation = [val / num_expert_trajectories for val in learner_feature_expectation] # Scale to match expert mass
            
            # Step B: Calculate Gradient
            gradient = [
                expert_feature_expectation[f] - learner_feature_expectation[f]
                for f in range(self.feature_dim)  
            ]
            
            # Step C: Update Reward Weights (Gradient Ascent)
            for f in range(self.feature_dim):
                self.learned_reward_weights[f] += self.learning_rate * gradient[f]
                
            # Log progress
            diff_norm = sum(abs(g) for g in gradient)
            feature_diff_history.append(diff_norm)
            if iteration % 5 == 0:
                weight_history.append(list(self.learned_reward_weights))
                
        # The learned weights now represent the "Intention" or "Reward" of the expert
        return {
            "expert_trajectories_analyzed": num_expert_trajectories,
            "training_iterations": num_iterations,
            "final_reward_weights": [round(w, 4) for w in self.learned_reward_weights],
            "initial_feature_divergence": round(feature_diff_history[0], 4),
            "final_feature_divergence": round(feature_diff_history[-1], 4),
            "mechanics": "Apprenticeship Learning via Maximum Entropy Inverse Reinforcement Learning. Reward function extraction by matching empirical feature expectations."
        }
