# Generated by Django 5.0.1 on 2026-05-15 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice (Single Correct)'), ('multiple_select', 'Multiple Choice (Multiple Correct)'), ('true_false', 'True/False'), ('numerical', 'Numerical Answer'), ('fill_blank', 'Fill in the Blank')], default='mcq', max_length=20)),
                ('difficulty', models.FloatField(default=0.5, help_text='IRT difficulty parameter (0-5)')),
                ('discrimination', models.FloatField(default=1.0, help_text='IRT discrimination parameter')),
                ('guess_factor', models.FloatField(default=0.25, help_text='IRT guessing parameter')),
                ('bloom_level', models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], default='understand', max_length=15)),
                ('explanation', models.TextField(help_text='Detailed explanation of the correct answer')),
                ('solution_steps', models.JSONField(blank=True, default=list, help_text='Step-by-step solution')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of topic tags')),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_model', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_prompt_version', models.CharField(blank=True, max_length=20, null=True)),
                ('ai_generation_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('avg_time_seconds', models.FloatField(default=0, help_text='Average time users take to answer')),
                ('is_verified', models.BooleanField(default=False, help_text='Manually verified by instructor')),
                ('reported_count', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.topic')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_bank',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, help_text='Why this option is correct/incorrect')),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='test_engine.question')),
            ],
            options={
                'db_table': 'question_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('practice', 'Practice Mode (untimed, instant feedback)'), ('mock', 'Mock Test (timed, no feedback until submit)'), ('timed_challenge', 'Timed Challenge (strict timer, leaderboard)'), ('adaptive', 'Adaptive Test (difficulty adjusts in real-time)'), ('review', 'Review Mode (see answers and explanations)')], default='mock', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed (auto-distributed)'), ('adaptive', 'Adaptive')], default='mixed', max_length=15)),
                ('time_limit_minutes', models.IntegerField(default=60)),
                ('passing_score', models.FloatField(default=50.0, help_text='Minimum percentage to pass')),
                ('total_marks', models.FloatField(default=0)),
                ('negative_marks_per_question', models.FloatField(default=0)),
                ('marks_per_correct', models.FloatField(default=1)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('generation_config', models.JSONField(blank=True, default=dict, help_text='AI generation parameters used')),
                ('ai_generation_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('cache_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('cache_ttl', models.IntegerField(default=86400, help_text='Cache TTL in seconds (default 24h)')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('attempt_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='exams.exam')),
            ],
            options={
                'db_table': 'tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('expired', 'Expired (time ran out)'), ('abandoned', 'Abandoned')], default='not_started', max_length=20)),
                ('mode', models.CharField(choices=[('practice', 'Practice Mode (untimed, instant feedback)'), ('mock', 'Mock Test (timed, no feedback until submit)'), ('timed_challenge', 'Timed Challenge (strict timer, leaderboard)'), ('adaptive', 'Adaptive Test (difficulty adjusts in real-time)'), ('review', 'Review Mode (see answers and explanations)')], default='mock', max_length=20)),
                ('score', models.FloatField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('device_info', models.JSONField(blank=True, default=dict, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('autosave_data', models.JSONField(blank=True, default=dict)),
                ('autosave_version', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='test_engine.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True, help_text='For numerical/fill-blank questions')),
                ('is_correct', models.BooleanField(blank=True, help_text='Null = not yet graded', null=True)),
                ('marks_obtained', models.FloatField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('first_answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False, help_text='Marked for review')),
                ('is_bookmarked', models.BooleanField(default=False, help_text='Bookmarked by user')),
                ('answer_changes', models.IntegerField(default=0)),
                ('selected_options', models.ManyToManyField(blank=True, related_name='attempt_answers', to='test_engine.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='test_engine.testattempt')),
            ],
            options={
                'db_table': 'attempt_answers',
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('marks', models.FloatField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='test_engine.test')),
            ],
            options={
                'db_table': 'test_questions',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'is_deleted'], name='question_ba_topic_i_105cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type', 'is_deleted'], name='question_ba_questio_41cd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty', 'is_deleted'], name='question_ba_difficu_fda92b_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['bloom_level', 'is_deleted'], name='question_ba_bloom_l_c5b52a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_ai_generated', 'is_deleted'], name='question_ba_is_ai_g_1c9e53_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_verified', 'is_deleted'], name='question_ba_is_veri_b6b3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['ai_generation_id'], name='question_ba_ai_gene_e5f662_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['question', 'is_correct'], name='question_op_questio_284133_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['exam', 'is_published'], name='tests_exam_id_48e9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['mode', 'is_published'], name='tests_mode_a259b7_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['difficulty', 'is_published'], name='tests_difficu_568305_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['is_featured', 'is_published'], name='tests_is_feat_6e1598_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['is_ai_generated', 'is_published'], name='tests_is_ai_g_0d1167_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'status'], name='test_attemp_user_id_e1839d_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', 'status'], name='test_attemp_test_id_3e23fc_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['status', 'started_at'], name='test_attemp_status_c9d7dd_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test'], name='test_attemp_user_id_b9f724_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['session_token'], name='test_attemp_session_1915f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('user', 'test', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['attempt', 'is_correct'], name='attempt_ans_attempt_cc4e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['attempt', 'is_flagged'], name='attempt_ans_attempt_6df369_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['attempt', 'is_bookmarked'], name='attempt_ans_attempt_2a1712_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['question'], name='attempt_ans_questio_7d3c13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attemptanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='testquestion',
            index=models.Index(fields=['test', 'order'], name='test_questi_test_id_2b886e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testquestion',
            unique_together={('test', 'question')},
        ),
    ]
