# Generated by Django 5.0.1 on 2026-06-04 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('test_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='test_engine.question'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.question'),
        ),
        migrations.AddField(
            model_name='test',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='test_engine.test'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='test_engine.testattempt'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_engine.question'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='test_engine.test'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'is_deleted'], name='question_ba_topic_i_105cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type', 'is_deleted'], name='question_ba_questio_41cd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty', 'is_deleted'], name='question_ba_difficu_fda92b_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['bloom_level', 'is_deleted'], name='question_ba_bloom_l_c5b52a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_ai_generated', 'is_deleted'], name='question_ba_is_ai_g_1c9e53_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_verified', 'is_deleted'], name='question_ba_is_veri_b6b3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['ai_generation_id'], name='question_ba_ai_gene_e5f662_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['question', 'is_correct'], name='question_op_questio_284133_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['exam', 'is_published'], name='tests_exam_id_48e9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['mode', 'is_published'], name='tests_mode_a259b7_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['difficulty', 'is_published'], name='tests_difficu_568305_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['is_featured', 'is_published'], name='tests_is_feat_6e1598_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['is_ai_generated', 'is_published'], name='tests_is_ai_g_0d1167_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'status'], name='test_attemp_user_id_e1839d_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', 'status'], name='test_attemp_test_id_3e23fc_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['status', 'started_at'], name='test_attemp_status_c9d7dd_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test'], name='test_attemp_user_id_b9f724_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['session_token'], name='test_attemp_session_1915f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('user', 'test', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['attempt', 'is_correct'], name='attempt_ans_attempt_cc4e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['attempt', 'is_flagged'], name='attempt_ans_attempt_6df369_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['attempt', 'is_bookmarked'], name='attempt_ans_attempt_2a1712_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['question'], name='attempt_ans_questio_7d3c13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attemptanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='testquestion',
            index=models.Index(fields=['test', 'order'], name='test_questi_test_id_2b886e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testquestion',
            unique_together={('test', 'question')},
        ),
    ]
