# Generated by Django 5.0.1 on 2026-07-04 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('test_engine', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['attempt', '-time_spent_seconds'], name='idx_answer_time'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['question', 'is_correct'], name='idx_answer_question_correct'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['attempt', 'answered_at'], name='idx_answer_attempt_time'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_by', '-created_at'], name='idx_question_creator'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'difficulty', 'is_deleted'], name='idx_question_topic_diff'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-usage_count'], name='idx_question_usage'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['verified_by', '-created_at'], name='idx_question_verified'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['created_by', '-created_at'], name='idx_test_creator'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['-attempt_count'], name='idx_test_attempts'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['exam', 'difficulty', 'is_published'], name='idx_test_exam_diff'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['-published_at'], name='idx_test_published'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', '-started_at'], name='idx_attempt_user_recent'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', '-score'], name='idx_attempt_test_score'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'passed', '-submitted_at'], name='idx_attempt_user_passed'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['-percentage'], name='idx_attempt_percentage'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['status', '-last_activity_at'], name='idx_attempt_activity'),
        ),
    ]
